from odoo.addons.aurora.tools.harness.repos.python.googleapis.python_storage_1356_to_1180 import *
from odoo.addons.aurora.tools.harness.repos.python.googleapis.python_storage_1356_to_1180 import *
from odoo.addons.aurora.tools.harness.repos.python.googleapis.python_storage_1172_to_703 import *
from odoo.addons.aurora.tools.harness.repos.python.googleapis.python_storage_679_to_534 import *
from odoo.addons.aurora.tools.harness.repos.python.googleapis.python_storage_679_to_534 import *
from odoo.addons.aurora.tools.harness.repos.python.googleapis.python_storage_526_to_325 import *
from odoo.addons.aurora.tools.harness.repos.python.googleapis.python_storage_325_to_41 import *
from odoo.addons.aurora.tools.harness.repos.python.googleapis.python_ndb_882_to_714 import *
from odoo.addons.aurora.tools.harness.repos.python.googleapis.python_ndb_702_to_665 import *
from odoo.addons.aurora.tools.harness.repos.python.googleapis.python_ndb_665_to_560 import *
from odoo.addons.aurora.tools.harness.repos.python.googleapis.google_cloud_python_11311_to_10219 import *
from odoo.addons.aurora.tools.harness.repos.python.googleapis.google_cloud_python_3514_to_3291 import *
from odoo.addons.aurora.tools.harness.repos.python.googleapis.google_cloud_python_2375_to_2223 import *
from odoo.addons.aurora.tools.harness.repos.python.googleapis.google_cloud_python_1787_to_1518 import *
from odoo.addons.aurora.tools.harness.repos.python.googleapis.google_cloud_python_55_to_20 import *
from odoo.addons.aurora.tools.harness.repos.python.googleapis.google_cloud_python_11311_to_10219 import *
