from odoo.addons.aurora.tools.harness.repos.python.sqlfluff.sqlfluff_6982_to_6010 import *
from odoo.addons.aurora.tools.harness.repos.python.sqlfluff.sqlfluff_6010_to_5286 import *
from odoo.addons.aurora.tools.harness.repos.python.sqlfluff.sqlfluff_6010_to_5286 import *
from odoo.addons.aurora.tools.harness.repos.python.sqlfluff.sqlfluff_5286_to_5181 import *
from odoo.addons.aurora.tools.harness.repos.python.sqlfluff.sqlfluff_5165_to_5070 import *
from odoo.addons.aurora.tools.harness.repos.python.sqlfluff.sqlfluff_5053_to_4813 import *
from odoo.addons.aurora.tools.harness.repos.python.sqlfluff.sqlfluff_4813_to_4335 import *
from odoo.addons.aurora.tools.harness.repos.python.sqlfluff.sqlfluff_4335_to_4326 import *
from odoo.addons.aurora.tools.harness.repos.python.sqlfluff.sqlfluff_4326_to_498 import *
from odoo.addons.aurora.tools.harness.repos.python.sqlfluff.sqlfluff_498_to_420 import *
from odoo.addons.aurora.tools.harness.repos.python.sqlfluff.sqlfluff_498_to_420 import *
from odoo.addons.aurora.tools.harness.repos.python.sqlfluff.sqlfluff_420_to_373 import *
from odoo.addons.aurora.tools.harness.repos.python.sqlfluff.sqlfluff_373_to_26 import *
