{
    "name": "Kensei",
    "version": "19.0.1.4.0",
    "category": "Tools",
    "summary": "Kensei — LLM task management with sandbox environments and file attachments",
    "description": """
        Kensei custom module for Ethara ETP.
        Full-featured OpenClaw integration with Docker/K8s sandbox environments.
        Includes file attachment support (images, documents, video) in chat via
        hybrid HTTP upload + WebSocket reference architecture.
    """,
    "author": "Ethara",
    "depends": ["base", "web", "hr", "bus", "mail", "etp_user_roles"],
    "data": [
        "security/kensei_security.xml",
        "security/kensei_tracker_security.xml",
        "security/ir.model.access.csv",
        "data/cron.xml",
        "data/tracker_sequence.xml",
        "data/persona_seed.xml",
        "data/domain_seed.xml",
        "views/res_config_settings_views.xml",
        "views/domain_views.xml",
        "views/persona_views.xml",
        "views/kensei_views.xml",
        "views/api_request_views.xml",
        "views/test_result_views.xml",
        "views/kensei_tracker_bulk_allocation_views.xml",
        "views/kensei_tracker_views.xml",
        "views/kensei_tracker_team_import_views.xml",
        "views/kensei_tracker_team_views.xml",
        "data/team_seed.xml",
        "views/menuitems.xml",
    ],
    "installable": True,
    "application": True,
    "license": "LGPL-3",
    "assets": {
        "web.assets_backend": [
            "kensei/static/src/views/fields/markdown_field/markdown_field.js",
            "kensei/static/src/views/fields/markdown_field/markdown_field.xml",
            "kensei/static/src/views/fields/markdown_field/markdown_field.scss",
            "kensei/static/src/views/fields/json_field/json_field.js",
            "kensei/static/src/views/fields/json_field/json_field.xml",
            "kensei/static/src/views/fields/json_field/json_field.scss",
            "kensei/static/src/sandbox_notification_service.js",
            "kensei/static/src/team_notification_service.js",
            "kensei/static/src/chat_service.js",
            "kensei/static/src/components/sandbox_iframe/sandbox_iframe.js",
            "kensei/static/src/components/sandbox_iframe/sandbox_iframe.xml",
            "kensei/static/src/components/sandbox_iframe/sandbox_iframe.scss",
            "kensei/static/src/components/task_progress/task_progress.js",
            "kensei/static/src/components/task_progress/task_progress.xml",
            "kensei/static/src/components/task_progress/task_progress.scss",
            "kensei/static/src/chat_widget/chat_widget.js",
            "kensei/static/src/chat_widget/chat_widget.xml",
            "kensei/static/src/chat_widget/chat_widget.scss",
            "kensei/static/src/components/gog_auth_dialog/gog_auth_dialog.js",
            "kensei/static/src/components/gog_auth_dialog/gog_auth_dialog.xml",
            "kensei/static/src/components/gog_auth_dialog/gog_auth_dialog.scss",
            "kensei/static/src/components/sandbox_card/sandbox_card.js",
            "kensei/static/src/components/sandbox_card/sandbox_card.xml",
            "kensei/static/src/components/sandbox_card/sandbox_card.scss",
            "kensei/static/src/task_dashboard/task_dashboard.js",
            "kensei/static/src/task_dashboard/task_dashboard.xml",
            "kensei/static/src/task_dashboard/task_dashboard.scss",
            "kensei/static/src/costing_dashboard/costing_dashboard.js",
            "kensei/static/src/costing_dashboard/costing_dashboard.xml",
            "kensei/static/src/costing_dashboard/costing_dashboard.scss",
            "kensei/static/src/tracker_common.js",
            "kensei/static/src/kensei_statusbar/kensei_statusbar.js",
            "kensei/static/src/tracker_dashboard/tracker_dashboard.js",
            "kensei/static/src/tracker_dashboard/tracker_dashboard.xml",
            "kensei/static/src/tracker_dashboard/tracker_dashboard.scss",
            "kensei/static/src/tasker_dashboard/tasker_dashboard.js",
            "kensei/static/src/tasker_dashboard/tasker_dashboard.xml",
            "kensei/static/src/tasker_dashboard/tasker_dashboard.scss",
            "kensei/static/src/tracker_daily/tracker_daily.js",
            "kensei/static/src/tracker_daily/tracker_daily.xml",
            "kensei/static/src/tracker_daily/tracker_daily.scss",
            "kensei/static/src/tracker_allocation.scss",
        ],
    },
}
