from odoo import models, fields, api
from odoo.exceptions import ValidationError, UserError
from datetime import datetime, date
import json
import logging

_logger = logging.getLogger(__name__)

QC_REVIEW_SYSTEM_PROMPT = """# SYSTEM PROMPT: Image Comparison QC Evaluator — Graphics Industry Standard

You are a senior QC auditor for AI-generated image comparison annotations in a production graphics pipeline. You have 15+ years in visual production, pre-press, VFX compositing, and editorial illustration. You do not tolerate sloppy evaluation. You have seen every shortcut annotators take and you catch them all.

You are reviewing an annotator's work. They were given:
- A TEXT PROMPT describing the desired image
- RESPONSE A (an AI-generated image)
- RESPONSE B (an AI-generated image)
- They scored: Overall Preference, Visual Quality (VQ), Absence of AI Artifacts (AI), and Instruction Following (IF)
- They may have written a justification comment

Your job: Determine if the annotator made the CORRECT call on each dimension and overall. Flag errors ruthlessly.

---

## EVALUATION FRAMEWORK (apply in this exact order)

### 1. INSTRUCTION FOLLOWING (IF) — The Prompt is God

- Read the prompt LITERALLY. Every noun, adjective, quantity, spatial relationship, action, and style descriptor is a binding requirement.
- If the prompt says "5 items" and the image shows 4 or 6, that is a FAILURE. No partial credit.
- If the prompt specifies a style (oil painting, pen and ink, colored pencil), the output MUST look like that medium was actually used — not "AI's interpretation of" that medium. Know the difference between actual oil painting texture and AI-generated plastic sheen pretending to be oil paint.
- Elements NOT requested in the prompt are VIOLATIONS. Extra objects, extra text, extra decorative elements = the image added what wasn't asked for. This is an IF failure for that response.
- Spatial relationships are NON-NEGOTIABLE. "Above," "below," "left of," "inside," "adjacent to" — verify each one. AI frequently scrambles spatial logic.
- If one image follows the prompt and the other doesn't, this is NEVER a "Tie." Period.
- Text rendering: If the prompt includes specific text (quotes, labels, titles), verify EXACT spelling, correct characters, no garbled letters, no missing words. A misspelled word is an automatic IF failure.

### 2. ABSENCE OF AI ARTIFACTS (AI) — The Slop Detector

You are looking for telltale signs the image was generated by a model that doesn't understand physical reality:

**Anatomy (ZERO TOLERANCE):**
- Extra or missing fingers, limbs, toes, ears
- Hands with impossible joint angles or fused fingers
- Eyes: mismatched pupils, wrong iris patterns for the species (e.g., tree frogs have horizontal/vertical slits, NOT cross-hatched pupils), asymmetric sizing
- Faces melting into backgrounds, smudged features on secondary characters
- Hair that defies gravity without reason, merges with clothing

**Physics & Logic (CRITICAL):**
- Objects defying gravity without explanation
- Reflections that don't match the source (mirrors, water, glass)
- Shadows pointing in contradictory directions
- Springs oriented wrong, mechanical parts that couldn't function
- Water flowing uphill, smoke going sideways without wind cues
- Motion blur on objects that shouldn't have it (a helium balloon doesn't blur — it floats UPWARD slowly)
- Ruler/measurement markings that are nonsensical or non-sequential

**Material & Surface:**
- Text on surfaces that warps incorrectly (signs, books, shirts)
- Textures that transition illogically (wood suddenly becomes stone)
- Metallic surfaces with impossible reflections
- Fabric that doesn't fold according to gravity and body shape

**Structural:**
- Buildings with impossible architecture (windows that lead nowhere, doors at wrong heights)
- Charts/diagrams where data doesn't match labels, axes are wrong, proportions are impossible
- Duplicate labels, numbers colored inconsistently, pie charts where slices don't match percentages
- Random characters/symbols appearing (Asian characters, symbols) where they don't belong

**The Edit Test:** Ask yourself — "If a production artist had to clean this up for a client deliverable, which image requires LESS work?" That image wins on AI artifacts.

### 3. VISUAL QUALITY (VQ) — Craft and Finish

- Composition: Is the subject well-framed? Does the eye flow naturally?
- Lighting: Consistent light source(s), appropriate shadows, believable highlights
- Color: Harmonious palette, appropriate saturation, no banding or posterization
- Detail: Appropriate level of detail for the style. Sharper ≠ always better. Match the requested medium.
- Image does NOT need to be photorealistic to score high VQ. A well-executed illustration style beats a muddy attempt at photorealism.
- Clarity of rendering at full resolution
- "Looks more polished" is NOT sufficient justification without specifics. WHAT looks more polished? Spacing? Typography? Color grading? Be specific or you've said nothing.

### 4. OVERALL PREFERENCE — Must Follow Logic

Overall Preference MUST be the logical consequence of the three dimension scores. If IF=A, AI=A, VQ=Tie, then Overall CANNOT be B. It's A. Math isn't hard.

Exception: If one dimension is so catastrophically failed that it overrides the others (e.g., IF is perfect but the image has a three-armed person), justify why the catastrophic failure dominates.

---

## RED FLAGS YOU MUST CATCH IN ANNOTATOR WORK

### 1. "TIE SPAM" / "ONE-SIDE SPAM"

If an annotator picks the same response for ALL dimensions and overall without acknowledging ANY weakness in their chosen response, this is likely lazy evaluation. Verify independently — it is statistically unlikely one image dominates perfectly across all axes.

### 2. "TIE BOTH GOOD" WHEN DEFECTS EXIST

This is the #1 annotator failure. If ONE image has a missing leg, melted face, wrong spelling, broken physics, or extra appendage — it is NOT "Both Good." The defective image LOSES that dimension. No exceptions.

### 3. "TIE BOTH BAD" WHEN ONE IS CLEARLY BETTER

Both can be imperfect, but if one is LESS broken, it wins. "Both Bad" means they are EQUALLY deficient — a high bar. If you can point to specific additional flaws in one that the other doesn't have, it's not a tie.

### 4. CONTRADICTORY JUSTIFICATION

If the annotator's written comment describes flaws in Response B but then selects B as the winner — flag immediately. Their own words condemn their choice. This often indicates the annotator used AI to write the comment without reading it.

### 5. IGNORING THE PROMPT'S IMPLICIT PHYSICS

"A helium balloon released from a height, shown 2 seconds later" — the balloon goes UP. If the image shows it falling with motion blur, that's IF AND AI failure. Annotators who don't understand basic physics will miss this.

### 6. DOMAIN IGNORANCE

- Alcatraz layout accuracy matters for a map prompt
- Archer fish behavior matters for a nature prompt
- Calligraphy technique matters for a calligraphy prompt
- Spring mechanics matter for a physics diagram
- Chart data integrity matters for an infographic prompt

If the annotator lacks domain knowledge and evaluates purely on "looks pretty," that's a failure. The prompt defines what "correct" means.

### 7. AI-GENERATED JUSTIFICATION COMMENTS

If the annotator's comment reads like generic AI output (overly balanced, acknowledges both sides without committing, uses phrases like "both responses follow the prompt well"), but their scores tell a different story — flag as suspected AI-written justification. A real evaluator's notes are terse, specific, and opinionated.

---

## SCORING THE ANNOTATOR

Rate each flagged annotation:

- **GOOD**: Correct calls across all dimensions. Justification (if present) is specific and defensible.
- **ACCEPTABLE**: Minor disagreement on one dimension, but overall preference is correct. The kind of call reasonable people could argue about.
- **BELOW EXPECTATIONS**: One or two dimensions scored incorrectly, but the annotator shows they were paying attention (just missed something). Coachable error.
- **UNACCEPTABLE**: Multiple dimensions wrong, evidence of spam/laziness, contradictory logic, clear indication the annotator did not carefully examine both images. This work cannot ship.

---

## YOUR OUTPUT FORMAT — STRICT JSON CONTRACT (mandatory)

Respond with EXACTLY one JSON object and NOTHING else.  No markdown
fences, no commentary before or after, no "Here is the JSON:"
preamble.  The first character of your reply MUST be `{` and the
last character MUST be `}`.  If you cannot determine a value, use
an empty string `""` — never `null` and never omit the key.

Use this exact schema (keys, casing, and enumerated values matter — the
parser is strict):

{
  "task_id": "string (echo the Task ID from the input)",
  "annotator": "string (echo the annotator name/email)",
  "prompt_summary": "string (one line, <= 200 chars)",
  "annotator_calls": {
    "OP": "A | B | Tie Both Good | Tie Both Bad",
    "VQ": "A | B | Tie Both Good | Tie Both Bad",
    "AI": "A | B | Tie Both Good | Tie Both Bad",
    "IF": "A | B | Tie Both Good | Tie Both Bad"
  },
  "assessment": {
    "IF": {"verdict": "Agree | Disagree", "reason": "string (terse, only required if Disagree)"},
    "AI": {"verdict": "Agree | Disagree", "reason": "string"},
    "VQ": {"verdict": "Agree | Disagree", "reason": "string"},
    "OP": {"verdict": "Agree | Disagree", "reason": "string"}
  },
  "flag_category": "Tie Spam | One-Side Spam | Tie Both Good with Defects | Contradictory Justification | Physics/Logic Miss | Domain Ignorance | AI-Written Comment | Clean",
  "score": "Good | Acceptable | Below Expectations | Unacceptable",
  "overall_feedback": "string (one paragraph, terse, specific, no hedging)",
  "notes": "string (bullet-style if needed, escape newlines as \\n)"
}

Hard rules:
- `score` MUST be one of the four exact strings above — same casing,
  same spacing.  Any other value (e.g. "GOOD", "good", "Below
  Expectations.") fails downstream parsing.
- `flag_category` MUST be one of the listed labels.  Use "Clean" if
  no flag applies.
- Every `verdict` MUST be exactly "Agree" or "Disagree".
- Do NOT wrap the JSON in triple-backticks.
- Do NOT prepend "json" or any other prefix.
- Do NOT include trailing commentary explaining the JSON.

---

## PRINCIPLES (burn these in)

- You are not here to be fair to the annotator. You are here to protect data quality.
- A wrong annotation that trains a model is worse than no annotation at all.
- "I can see why they picked that" is NOT a defense if they're wrong.
- When in doubt, the prompt wins. Always. The prompt is the client brief. Miss the brief, lose the client.
- Pretty garbage is still garbage. An image can be beautiful and completely wrong.
- If you wouldn't sign off on this going to a client at a top-5 agency, it doesn't pass.
- Think like a retoucher who bills $200/hr: which image saves you more time? That's your answer."""


class TaskForgeLog(models.Model):
    _name = 'task.forge.log'
    _description = 'Task Forge Task Log'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _order = 'create_date desc'

    name = fields.Char(string='Task Name', required=True, tracking=True)
    sequence = fields.Char(string='Reference', readonly=True, copy=False, default='New')
    employee_id = fields.Many2one(
        'hr.employee', string='Tasker', required=True,
        default=lambda self: self.env.user.employee_id,
        tracking=True,
    )
    project_id = fields.Many2one('project.project', string='Project', tracking=True)
    is_justification_required = fields.Boolean(related='project_id.is_justification_required')

    date = fields.Date(string='Date', default=fields.Date.context_today, required=True)
    state = fields.Selection([
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
        ('qc_approved', 'QC Approved'),
        ('qc_rejected', 'QC Rejected'),
        ('blocker', 'Blocker'),
        ('returned', 'Returned'),
        ('ack', 'Acknowledged'),
        ('escalated', 'Escalated'),
        ('overdue', 'Overdue'),
    ], string='Status', default='in_progress', tracking=True)

    start_time = fields.Datetime(string='Start Time')
    end_time = fields.Datetime(string='End Time')
    time_taken_mins = fields.Integer(
        string='Time Taken (mins)',
        compute='_compute_time_taken',
        store=True,
    )
    pause_time = fields.Char(string="Pause Time")
    start_screenshot_url = fields.Char(string='Start Screenshot URL')
    end_screenshot_url = fields.Char(string='End Screenshot URL')

    blocker_reason = fields.Text(string='Blocker Reason')
    quality_score = fields.Integer(string='Quality Score')
    prompt_justification = fields.Text(string='Prompt Justification')
    prompt_text = fields.Text(string='Prompt')
    justification_text = fields.Text(string='Justification')
    feedback_note = fields.Text(string='Feedback Note')

    grammar_checked = fields.Boolean(string='Grammar Checked', default=False, index=True)
    grammar_is_perfect = fields.Boolean(string='Grammar Perfect', default=False, index=True)
    prompt_error_percentage = fields.Float(string='Prompt Error %', default=0)
    justification_error_percentage = fields.Float(string='Justification Error %', default=0)
    prompt_issue_count = fields.Integer(string='Prompt Issues', default=0)
    justification_issue_count = fields.Integer(string='Justification Issues', default=0)
    total_grammar_issues = fields.Integer(string='Total Grammar Issues', default=0, index=True)
    prompt_corrected = fields.Text(string='Corrected Prompt')
    justification_corrected = fields.Text(string='Corrected Justification')

    prompt_grammar_count = fields.Integer(string='Prompt Grammar Errors', default=0)
    prompt_misspelling_count = fields.Integer(string='Prompt Misspelling Errors', default=0)
    prompt_punctuation_count = fields.Integer(string='Prompt Punctuation Errors', default=0)
    prompt_clarity_count = fields.Integer(string='Prompt Clarity Errors', default=0)
    prompt_typography_count = fields.Integer(string='Prompt Typography Errors', default=0)
    prompt_capitalization_count = fields.Integer(string='Prompt Capitalization Errors', default=0)
    prompt_miscellaneous_count = fields.Integer(string='Prompt Miscellaneous Errors', default=0)

    justification_grammar_count = fields.Integer(string='Justification Grammar Errors', default=0)
    justification_misspelling_count = fields.Integer(string='Justification Misspelling Errors', default=0)
    justification_punctuation_count = fields.Integer(string='Justification Punctuation Errors', default=0)
    justification_clarity_count = fields.Integer(string='Justification Clarity Errors', default=0)
    justification_typography_count = fields.Integer(string='Justification Typography Errors', default=0)
    justification_capitalization_count = fields.Integer(string='Justification Capitalization Errors', default=0)
    justification_miscellaneous_count = fields.Integer(string='Justification Miscellaneous Errors', default=0)

    grammar_input_tokens = fields.Integer(string='Grammar Input Tokens', default=0)
    grammar_output_tokens = fields.Integer(string='Grammar Output Tokens', default=0)

    blocker_ids = fields.One2many('task.forge.blocker', 'task_id', string='Blockers')
    bug_report_ids = fields.One2many('task.forge.bug.report', 'task_id', string='Bug Reports')
    rubric_rating_ids = fields.One2many(
        'task.forge.rubric.rating', 'log_id', string='Rubric Ratings',
    )
    rubric_completed = fields.Boolean(
        string='Rubric Completed',
        compute='_compute_rubric_completed',
        store=True,
    )

    response_ids = fields.One2many(
        'task.forge.response', 'task_id', string='Responses',
    )
    response_completed = fields.Boolean(
        string='Responses Completed',
        compute='_compute_response_completed',
        store=True,
    )

    employee_name = fields.Char(related='employee_id.name', store=True)
    project_name = fields.Char(related='project_id.name', store=True)
    image_url_lines = fields.One2many('task.forge.image', 'task_id', string="Image Url Lines")
    chain_of_thought = fields.Text(string='Chain of Thought')

    # QC Review
    reviewed_by_id = fields.Many2one('hr.employee', string='Reviewed By', readonly=True)
    review_date = fields.Datetime(string='Review Date', readonly=True)
    rejection_reason = fields.Text(string='Rejection Reason')

    # LLM QC Results
    qc_llm_score = fields.Selection([
        ('good', 'Good'),
        ('acceptable', 'Acceptable'),
        ('below_expectations', 'Below Expectations'),
        ('unacceptable', 'Unacceptable'),
    ], string='LLM QC Score')
    qc_llm_flag = fields.Char(string='LLM QC Flag')
    qc_llm_feedback = fields.Text(string='LLM QC Feedback')
    qc_llm_raw_response = fields.Text(string='LLM QC Raw Response')
    qc_llm_input_tokens = fields.Integer(string='Input Tokens', default=0)
    qc_llm_output_tokens = fields.Integer(string='Output Tokens', default=0)

    # --- Rich per-dimension QC result (populated from the new JSON contract) ---
    qc_llm_prompt_summary = fields.Char(string='LLM Prompt Summary')
    qc_llm_notes = fields.Text(string='LLM QC Notes')
    # Echoed annotator calls — useful to confirm the LLM read the
    # rubric correctly before believing its verdicts.
    qc_llm_annotator_op = fields.Char(string='Annotator OP (echoed)')
    qc_llm_annotator_vq = fields.Char(string='Annotator VQ (echoed)')
    qc_llm_annotator_ai = fields.Char(string='Annotator AI (echoed)')
    qc_llm_annotator_if = fields.Char(string='Annotator IF (echoed)')
    # Per-dimension verdict + reason.  Selection enforces the prompt's
    # "Agree" / "Disagree" contract; the reason is free text.
    _qc_verdict_selection = [('agree', 'Agree'), ('disagree', 'Disagree')]
    qc_llm_if_verdict = fields.Selection(_qc_verdict_selection, string='IF Verdict')
    qc_llm_if_reason = fields.Text(string='IF Reason')
    qc_llm_ai_verdict = fields.Selection(_qc_verdict_selection, string='AI Verdict')
    qc_llm_ai_reason = fields.Text(string='AI Reason')
    qc_llm_vq_verdict = fields.Selection(_qc_verdict_selection, string='VQ Verdict')
    qc_llm_vq_reason = fields.Text(string='VQ Reason')
    qc_llm_op_verdict = fields.Selection(_qc_verdict_selection, string='OP Verdict')
    qc_llm_op_reason = fields.Text(string='OP Reason')

    # Rating System

    rubric_text = fields.Text(string='Rubric Text')

    def action_parse_rubric_text(self):
        self.ensure_one()
        if not self.rubric_text:
            raise UserError('Please paste rubric text first.')
        if not self.project_id:
            raise UserError('Select a project first.')

        from odoo.addons.task_forge_core.services.rubric_text_parser import (
            parse_rubric_text, match_and_create_rubric
        )

        parsed = parse_rubric_text(self.rubric_text)
        if not parsed:
            raise UserError('Could not parse any rubric structure from the text.')

        result = match_and_create_rubric(self.env, self.project_id, parsed)

        new_dims = [d for d in result['dimensions'] if d['is_new']]
        new_opts = [o for o in result['options'] if o['is_new']]

        msg = f"{len(new_dims)} new dimension(s) and {len(new_opts)} new option(s) created as temp. PL needs to approve them in project settings before they appear on tasks."
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': 'Rubric Parsed',
                'message': msg,
                'type': 'success' if (new_dims or new_opts) else 'info',
                'sticky': False,
            }
        }

    # Rating Syste
    task_score = fields.Integer(string='Task Score')
    comment = fields.Char(string='Comment')

    @api.depends('start_time', 'end_time')
    def _compute_time_taken(self):
        for rec in self:
            if rec.start_time and rec.end_time:
                delta = rec.end_time - rec.start_time
                rec.time_taken_mins = int(delta.total_seconds() / 60)
            else:
                rec.time_taken_mins = 0

    @api.depends(
        'project_id', 'project_id.is_rubrics_required',
        'project_id.rubric_category_ids',
        'project_id.rubric_category_ids.dimension_ids',
        'project_id.rubric_category_ids.dimension_ids.is_required',
        'rubric_rating_ids', 'rubric_rating_ids.dimension_id',
    )
    def _compute_rubric_completed(self):
        for rec in self:
            project = rec.project_id
            if not project or not project.is_rubrics_required:
                rec.rubric_completed = True
                continue
            required_dims = self.env['rubric.dimension']
            for cat in project.rubric_category_ids:
                required_dims |= cat.dimension_ids.filtered(lambda d: d.is_required)
            if not required_dims:
                rec.rubric_completed = True
                continue
            rated_dim_ids = set(rec.rubric_rating_ids.mapped('dimension_id.id'))
            rec.rubric_completed = all(d.id in rated_dim_ids for d in required_dims)

    @api.depends(
        'project_id', 'project_id.is_response_required',
        'project_id.no_of_responses',
        'response_ids', 'response_ids.value',
    )
    def _compute_response_completed(self):
        for rec in self:
            project = rec.project_id
            if not project or not project.is_response_required:
                rec.response_completed = True
                continue
            required_count = project.no_of_responses or 0
            if not required_count:
                rec.response_completed = True
                continue
            filled = rec.response_ids.filtered(lambda r: r.value)
            rec.response_completed = len(filled) >= required_count

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get('sequence', 'New') == 'New':
                vals['sequence'] = self.env['ir.sequence'].next_by_code('task.forge.log') or 'New'
        return super().create(vals_list)

    def _check_punch_in(self, employee_id):
        """Verify the employee has an active attendance record for today."""
        today = date.today()
        attendance = self.env['hr.attendance'].sudo().search([
            ('employee_id', '=', employee_id),
            ('check_in', '>=', datetime.combine(today, datetime.min.time())),
            ('check_in', '<', datetime.combine(today, datetime.max.time())),
        ], limit=1)
        if not attendance:
            raise UserError('You must punch in before starting a task.')
        return attendance

    def _check_no_active_task(self, employee_id):
        """Ensure no other task is in_progress for this employee."""
        active = self.sudo().search([
            ('employee_id', '=', employee_id),
            ('state', '=', 'in_progress'),
        ], limit=1)
        if active:
            raise UserError(f'You already have an active task: {active.name}. End it first.')

    def action_start(self):
        """Start a task - called from API."""
        self.ensure_one()
        self._check_punch_in(self.employee_id.id)
        # self._check_no_active_task(self.employee_id.id)
        self.write({
            'state': 'in_progress',
            'start_time': datetime.now(),
        })

    @api.model
    def _cron_inactivity_check(self):
        """Find members inactive 3+ days and notify their PLs."""
        from datetime import timedelta
        today = date.today()
        three_days_ago = today - timedelta(days=3)
        Employee = self.env['hr.employee'].sudo()
        Attendance = self.env['hr.attendance'].sudo()
        Notification = self.env['kubera.notification'].sudo()

        active_employees = Employee.search([('task_forge_active', '=', True)])
        for emp in active_employees:
            role = emp._get_task_forge_role()
            if role != 'tasker':
                continue
            recent = Attendance.search_count([
                ('employee_id', '=', emp.id),
                ('check_in', '>=', datetime.combine(three_days_ago, datetime.min.time())),
            ])
            if recent == 0 and emp.task_forge_pl_id and emp.task_forge_pl_id.user_id:
                Notification.create({
                    'title': 'Inactivity Alert',
                    'message': f'{emp.name} has been inactive for 3+ days.',
                    'user_id': emp.task_forge_pl_id.user_id.id,
                    'priority': '2',
                })

    def action_qc_with_llm(self):
        self.ensure_one()
        if not self.project_id:
            raise UserError('Task must have a project assigned for QC.')
        if not self.project_id.is_rubrics_required:
            raise UserError('This project does not have rubrics configured.')

        categories = self.project_id.rubric_category_ids
        if not categories:
            raise UserError('No rubric categories configured for this project.')

        rubric_spec = []
        for cat in categories:
            dims = []
            for dim in cat.dimension_ids:
                opts = [{'id': o.id, 'name': o.name, 'value': o.value} for o in dim.option_ids]
                dims.append({
                    'dimension_id': dim.id,
                    'name': dim.name,
                    'description': dim.description or '',
                    'is_required': dim.is_required,
                    'options': opts,
                })
            rubric_spec.append({
                'category': cat.name,
                'description': cat.description or '',
                'dimensions': dims,
            })

        annotator_ratings = ''
        if self.rubric_rating_ids:
            for r in self.rubric_rating_ids:
                dim_name = r.dimension_name_snapshot or (r.dimension_id.name or '')
                opt_name = r.option_name_snapshot or (r.option_id.name or '')
                annotator_ratings += f"\n  {dim_name} = {opt_name}"

        responses_text = ''
        images = []
        if self.response_ids:
            for r in self.response_ids.sorted('sequence'):
                if r.response_url:
                    from odoo.addons.task_forge_core.services.kimi_client import fetch_image_as_base64
                    b64, media_type = fetch_image_as_base64(r.response_url)
                    if b64:
                        fmt = media_type.split('/')[-1] if media_type else 'jpeg'
                        images.append({'base64': b64, 'format': fmt})
                        responses_text += f"\n  Response {r.sequence}: (image {len(images)} attached as image block)"
                    else:
                        responses_text += f"\n  Response {r.sequence}: (FAILED to download from {r.response_url})"
                else:
                    responses_text += f"\n  Response {r.sequence}: (no URL provided)"

        _logger.info('QC Review: %d images downloaded for task %d', len(images), self.id)

        user_content = f"Task ID: {self.id}\n"
        user_content += f"Task Name: {self.name or ''}\n"
        user_content += f"Annotator: {self.employee_id.name or ''}\n\n"
        user_content += f"Prompt: {self.prompt_text or '(none)'}\n\n"
        user_content += f"Justification/Comment: {self.justification_text or '(none)'}\n\n"
        user_content += f"Chain of Thought: {self.chain_of_thought or '(none)'}\n\n"
        if responses_text:
            user_content += f"Images (Response A=image 1, Response B=image 2, etc.):{responses_text}\n\n"
        if annotator_ratings:
            user_content += f"Annotator's Ratings:{annotator_ratings}\n\n"
        user_content += f"Rubric Schema:\n{json.dumps(rubric_spec, indent=2)}"

        system_prompt = QC_REVIEW_SYSTEM_PROMPT

        from odoo.addons.task_forge_core.services.kimi_client import call_kimi, parse_json_response

        result = call_kimi(system_prompt, user_content, temperature=0.1, images=images if images else None)
        raw_text = result.get('text', '')
        _logger.info('QC LLM response (%d chars): %s', len(raw_text), raw_text[:500])

        usage = result.get('usage', {})
        input_tokens = usage.get('input_tokens', 0)
        output_tokens = usage.get('output_tokens', 0)

        parsed = parse_json_response(raw_text)
        if not parsed:
            # Save raw response so the operator can inspect what the
            # LLM actually said.  Include a short snippet in the
            # UserError so the cause is visible without leaving the
            # popup — going to read the Raw LLM Response field on the
            # form is one extra click most people skip.
            preview = (raw_text or '').strip().replace('\n', ' ')[:240]
            self.write({
                'qc_llm_raw_response': raw_text,
                'qc_llm_feedback': 'LLM returned invalid JSON. See raw response.',
                'qc_llm_input_tokens': input_tokens,
                'qc_llm_output_tokens': output_tokens,
            })
            raise UserError(
                'LLM returned an invalid response (no parseable JSON '
                'object found).  Raw reply saved in the Raw LLM Response '
                'field.\n\nFirst 240 chars:\n%s' % preview
            )

        # --- Pull the new structured shape, tolerating the old flat
        # one as well so a prompt rollback doesn't break the wiring. ---
        overall_feedback = parsed.get('overall_feedback', '') or ''
        flag_category = parsed.get('flag_category', '') or ''
        notes = parsed.get('notes', '') or ''
        prompt_summary = parsed.get('prompt_summary', '') or ''

        # ``score`` must match one of four exact strings — accept loose
        # casing / extra punctuation defensively (the prompt is strict
        # but Kimi sometimes returns "good" or "Good." anyway).
        raw_score = parsed.get('score', '') or ''
        score = (raw_score or '').strip().rstrip('.').strip()
        score_map = {
            'good': 'good',
            'acceptable': 'acceptable',
            'below expectations': 'below_expectations',
            'unacceptable': 'unacceptable',
        }
        score_value = score_map.get(score.lower(), False)

        # Echoed annotator calls — `annotator_calls` is nested in the
        # new schema; fall back to flat keys if the model flattened it.
        annot = parsed.get('annotator_calls') or {}
        annot_op = annot.get('OP') or parsed.get('annotator_op', '')
        annot_vq = annot.get('VQ') or parsed.get('annotator_vq', '')
        annot_ai = annot.get('AI') or parsed.get('annotator_ai', '')
        annot_if = annot.get('IF') or parsed.get('annotator_if', '')

        # Per-dimension assessment.  Each entry is supposed to be
        # ``{"verdict": "...", "reason": "..."}`` but tolerate a bare
        # string ("Agree") too — the prompt drift will eventually
        # happen.
        def _verdict(entry):
            if isinstance(entry, dict):
                v = (entry.get('verdict') or '').strip().lower()
            elif isinstance(entry, str):
                v = entry.strip().lower()
            else:
                v = ''
            if v.startswith('agree'):
                return 'agree'
            if v.startswith('disagree'):
                return 'disagree'
            return False

        def _reason(entry):
            if isinstance(entry, dict):
                return entry.get('reason') or ''
            return ''

        assessment = parsed.get('assessment') or {}
        if_v, if_r = _verdict(assessment.get('IF')), _reason(assessment.get('IF'))
        ai_v, ai_r = _verdict(assessment.get('AI')), _reason(assessment.get('AI'))
        vq_v, vq_r = _verdict(assessment.get('VQ')), _reason(assessment.get('VQ'))
        op_v, op_r = _verdict(assessment.get('OP')), _reason(assessment.get('OP'))

        # If score couldn't be mapped, fall back to inspecting the raw
        # string so we don't silently drop a verdict the model emitted
        # in an unexpected case.
        if not score_value and raw_score:
            _logger.warning(
                'QC LLM: unrecognised score value %r — leaving qc_llm_score blank',
                raw_score,
            )

        self.write({
            'qc_llm_score': score_value,
            'qc_llm_flag': flag_category,
            'qc_llm_feedback': overall_feedback,
            'qc_llm_raw_response': raw_text,
            'feedback_note': overall_feedback or notes,
            'qc_llm_input_tokens': input_tokens,
            'qc_llm_output_tokens': output_tokens,
            # New rich fields.
            'qc_llm_prompt_summary': prompt_summary,
            'qc_llm_notes': notes,
            'qc_llm_annotator_op': annot_op,
            'qc_llm_annotator_vq': annot_vq,
            'qc_llm_annotator_ai': annot_ai,
            'qc_llm_annotator_if': annot_if,
            'qc_llm_if_verdict': if_v, 'qc_llm_if_reason': if_r,
            'qc_llm_ai_verdict': ai_v, 'qc_llm_ai_reason': ai_r,
            'qc_llm_vq_verdict': vq_v, 'qc_llm_vq_reason': vq_r,
            'qc_llm_op_verdict': op_v, 'qc_llm_op_reason': op_r,
        })

        notify_msg = 'QC Review complete.'
        if raw_score:
            notify_msg += f' Score: {raw_score}.'
        if flag_category and flag_category.lower() != 'clean':
            notify_msg += f' Flag: {flag_category}.'

        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': 'QC Review Complete',
                'message': notify_msg,
                'type': 'success' if score_value in ('good', 'acceptable') else 'warning',
                'sticky': False,
            }
        }

    def action_end(self, end_screenshot_url=None, blocker_reason=None):
        """End a task with either completion or blocker."""
        self.ensure_one()
        vals = {
            'end_time': datetime.now(),
        }
        if end_screenshot_url:
            vals['end_screenshot_url'] = end_screenshot_url
            vals['image_url_lines'] = [(0, 0, {'image_url': end_screenshot_url, 'image_type': 'end'})]

        if blocker_reason:
            vals['state'] = 'blocker'
            vals['blocker_reason'] = blocker_reason
            self.write(vals)
            # Create blocker record
            blocker = self.env['task.forge.blocker'].sudo().create({
                'name': blocker_reason[:100],
                'task_id': self.id,
                'employee_id': self.employee_id.id,
                'qr_id': self.employee_id.task_forge_qr_id.id if self.employee_id.task_forge_qr_id else False,
                'pl_id': self.employee_id.task_forge_pl_id.id if self.employee_id.task_forge_pl_id else False,
                'blocker_reason': blocker_reason,
                'state': 'pending',
            })
            # Notify QR
            if self.employee_id.task_forge_qr_id and self.employee_id.task_forge_qr_id.user_id:
                self.env['kubera.notification'].sudo().create({
                    'title': 'New Blocker Raised',
                    'message': f'{self.employee_id.name} reported a blocker on task "{self.name}": {blocker_reason[:200]}',
                    'user_id': self.employee_id.task_forge_qr_id.user_id.id,
                    'priority': '2',
                    'res_model': 'task.forge.blocker',
                    'res_id': blocker.id,
                    'project_id': self.project_id.id if self.project_id else False,
                })
            return blocker
        else:
            vals['state'] = 'completed'
            self.write(vals)
            return self

class TaskForgeImages(models.Model):
    _name = 'task.forge.image'

    image_url = fields.Char(string='Image URL')
    image_type = fields.Selection([('start', 'Start'), ('end', 'End')])
    task_id = fields.Many2one('task.forge.log', string='Task')
    status = fields.Selection([('draft', 'Draft'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='draft')


