from odoo.addons.aurora.tools.harness.repos.python.microsoft.electionguard_python_1_2_1 import *
from odoo.addons.aurora.tools.harness.repos.python.microsoft.electionguard_python_1_2_3 import *
from odoo.addons.aurora.tools.harness.repos.python.microsoft.electionguard_python_1_2_2 import *
from odoo.addons.aurora.tools.harness.repos.python.microsoft.electionguard_python_1_3_0 import *
from odoo.addons.aurora.tools.harness.repos.python.microsoft.graspologic_1018_to_1017 import *
from odoo.addons.aurora.tools.harness.repos.python.microsoft.torchgeo_1441_to_928 import *
from odoo.addons.aurora.tools.harness.repos.python.microsoft.autogen_6071_to_5839 import *
from odoo.addons.aurora.tools.harness.repos.python.microsoft.autogen_5183_to_4847 import *
from odoo.addons.aurora.tools.harness.repos.python.microsoft.autogen_4400_to_4053 import *
from odoo.addons.aurora.tools.harness.repos.python.microsoft.autogen_3557_to_3481 import *
from odoo.addons.aurora.tools.harness.repos.python.microsoft.autogen_1963_to_1569 import *
from odoo.addons.aurora.tools.harness.repos.python.microsoft.torchgeo_1985_to_1441 import *
from odoo.addons.aurora.tools.harness.repos.python.microsoft.torchgeo_2840_to_2432 import *
