from odoo.addons.aurora.tools.harness.repos.python.pvlib.pvlib_python_2451_to_2291 import *
from odoo.addons.aurora.tools.harness.repos.python.pvlib.pvlib_python_2291_to_1991 import *
from odoo.addons.aurora.tools.harness.repos.python.pvlib.pvlib_python_1977_to_1567 import *
from odoo.addons.aurora.tools.harness.repos.python.pvlib.pvlib_python_1562_to_1368 import *
from odoo.addons.aurora.tools.harness.repos.python.pvlib.pvlib_python_1231_to_1160 import *
from odoo.addons.aurora.tools.harness.repos.python.pvlib.pvlib_python_1157_to_938 import *
from odoo.addons.aurora.tools.harness.repos.python.pvlib.pvlib_python_938_to_816 import *
from odoo.addons.aurora.tools.harness.repos.python.pvlib.pvlib_python_815_to_599 import *
from odoo.addons.aurora.tools.harness.repos.python.pvlib.pvlib_python_218_to_108 import *
from odoo.addons.aurora.tools.harness.repos.python.pvlib.pvlib_python_100_to_7 import *
