[service]
name = "google-classroom-api"
port = 8002
env_var_name = "GOOGLE_CLASSROOM_API_URL"
healthcheck_path = "/health"

[k8s]
image = ""
cpu_request = "25m"
memory_request = "128Mi"
memory_limit = "256Mi"
