from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_6_7_3 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_6_9_1 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_5_6_5 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_5_7_3 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_5_3 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_5_1_1 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_6_8_2 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_6_0_1 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_5_6_7 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_5_6_1 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_6_9_0 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_5_6_6 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_5_5 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_6_1_2 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_6_7_2 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_5_6_9 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_6_7_0 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_5_6_2 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_6_9_2 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_6_7_1 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_5_7_0 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_6_8_0 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_6_4_3 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_5_6 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_6_4_4 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_3609_to_3433 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_3394_to_3054 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_3054_to_2557 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_2549_to_2543 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_2070_to_2007 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_1999_to_1982 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_1982_to_1936 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_1713_to_1500 import *
from odoo.addons.aurora.tools.harness.repos.python.Pyomo.pyomo_1221_to_736 import *
