from odoo.addons.aurora.tools.harness.repos.python.pypa.pip_12729_to_12308 import *
from odoo.addons.aurora.tools.harness.repos.python.pypa.pip_9393_to_9208 import *
from odoo.addons.aurora.tools.harness.repos.python.pypa.pip_9208_to_9207 import *
from odoo.addons.aurora.tools.harness.repos.python.pypa.pip_8026_to_7704 import *
from odoo.addons.aurora.tools.harness.repos.python.pypa.pip_7704_to_7500 import *
from odoo.addons.aurora.tools.harness.repos.python.pypa.pip_6723_to_6402 import *
from odoo.addons.aurora.tools.harness.repos.python.pypa.pip_5764_to_5457 import *
from odoo.addons.aurora.tools.harness.repos.python.pypa.pip_5203_to_5136 import *
from odoo.addons.aurora.tools.harness.repos.python.pypa.pip_5629_to_4936 import *
from odoo.addons.aurora.tools.harness.repos.python.pypa.pip_7198_to_5124 import *
from odoo.addons.aurora.tools.harness.repos.python.pypa.pip_10840_to_6004 import *
from odoo.addons.aurora.tools.harness.repos.python.pypa.pip_13788_to_8796 import *
from odoo.addons.aurora.tools.harness.repos.python.pypa.pipenv_6385_to_6240 import *
from odoo.addons.aurora.tools.harness.repos.python.pypa.pipenv_6017_to_5826 import *
from odoo.addons.aurora.tools.harness.repos.python.pypa.pipenv_5826_to_5606 import *
from odoo.addons.aurora.tools.harness.repos.python.pypa.pipenv_5083_to_5026 import *
from odoo.addons.aurora.tools.harness.repos.python.pypa.pipenv_4874_to_4533 import *
from odoo.addons.aurora.tools.harness.repos.python.pypa.pipenv_1767_to_1621 import *
from odoo.addons.aurora.tools.harness.repos.python.pypa.pipenv_1426_to_1097 import *
from odoo.addons.aurora.tools.harness.repos.python.pypa.setuptools_4985_to_4565 import *
from odoo.addons.aurora.tools.harness.repos.python.pypa.setuptools_3212_to_2878 import *
from odoo.addons.aurora.tools.harness.repos.python.pypa.setuptools_1520_to_1365 import *
from odoo.addons.aurora.tools.harness.repos.python.pypa.setuptools_1365_to_1364 import *
from odoo.addons.aurora.tools.harness.repos.python.pypa.setuptools_1103_to_809 import *
from odoo.addons.aurora.tools.harness.repos.python.pypa.setuptools_809_to_716 import *
from odoo.addons.aurora.tools.harness.repos.python.pypa.cibuildwheel_342_to_315 import *
from odoo.addons.aurora.tools.harness.repos.python.pypa.cibuildwheel_1588_to_1091 import *
