{
    "name": "T2AV - Video Generation",
    "version": "19.0.1.18.10",
    "category": "Tools",
    "summary": "Generate videos from prompts via OpenRouter Seedance 2.0",
    "author": "Ethara",
    "license": "LGPL-3",
    "depends": ["base", "web", "mail", "bus", "s3_connector"],
    "external_dependencies": {
        "python": ["boto3", "cryptography", "requests", "pika", "python-dotenv"],
    },
    "data": [
        "security/t2av_security.xml",
        "security/ir.model.access.csv",
        "security/t2av_record_rules.xml",
        "security/t2av_consumer_security.xml",
        "data/t2av_sequence.xml",
        "data/t2av_category_sequences.xml",
        "data/t2av_sequence_sheet_sequences.xml",
        "data/ir_cron.xml",
        "data/t2av_server_actions.xml",
        "data/t2av_rabbitmq_data.xml",
        "data/t2av_stack_actions.xml",
        "views/t2av_batch_publish_wizard_views.xml",
        "views/t2av_generation_views.xml",
        "views/res_config_settings_views.xml",
        "views/t2av_import_wizard_views.xml",
        "views/t2av_review_override_wizard_views.xml",
        "views/t2av_stack_review_wizard_views.xml",
        "views/t2av_video_review_admin_views.xml",
        "views/t2av_sequence_sheet_row_views.xml",
        "views/t2av_sequence_sheet_export_wizard_views.xml",
        "views/t2av_menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "t2av/static/src/scss/t2av.scss",
            "t2av/static/src/components/live_status/live_status.js",
            "t2av/static/src/components/live_status/live_status.xml",
            "t2av/static/src/components/live_status/live_status.scss",
            "t2av/static/src/components/video_player/video_player.js",
            "t2av/static/src/components/video_player/video_player.xml",
            "t2av/static/src/components/cog_menu_patch/cog_menu_patch.js",
            "t2av/static/src/components/cog_menu_patch/list_view_patch.xml",
        ],
    },
    "application": True,
    "installable": True,
}
