from odoo.addons.aurora.tools.harness.repos.python.huggingface.datasets_1626_to_403 import *
from odoo.addons.aurora.tools.harness.repos.python.huggingface.datasets_3088_to_2608 import *
from odoo.addons.aurora.tools.harness.repos.python.huggingface.datasets_4322_to_3382 import *
from odoo.addons.aurora.tools.harness.repos.python.huggingface.datasets_5079_to_4372 import *
from odoo.addons.aurora.tools.harness.repos.python.huggingface.datasets_5582_to_5113 import *
from odoo.addons.aurora.tools.harness.repos.python.huggingface.datasets_6477_to_6045 import *
from odoo.addons.aurora.tools.harness.repos.python.huggingface.datasets_7009_to_6500 import *
from odoo.addons.aurora.tools.harness.repos.python.huggingface.diffusers_10261_to_8947 import *
from odoo.addons.aurora.tools.harness.repos.python.huggingface.diffusers_11323_to_10347 import *
from odoo.addons.aurora.tools.harness.repos.python.huggingface.transformers import *
from odoo.addons.aurora.tools.harness.repos.python.huggingface.transformers_44040_to_3323 import *
