{
    'name': 'Ethara HRMS Extension',
    'version': '19.0.1.0.5',
    'summary': 'Extends hr.job and hr.applicant with Ethara AI job posting + application fields',
    'description': 'Adds job posting metadata (slug, work mode, salary, responsibilities, approval workflow, screening prompt, etc.) to hr.job and portfolio/github/resume URLs plus cancellation tracking to hr.applicant.',
    'category': 'Human Resources/Recruitment',
    'depends': ['base', 'hr', 'hr_recruitment', 'mail', 'api_auth_gateway'],
    'external_dependencies': {'python': ['requests', 'PyPDF2']},
    'data': [
        'security/ir.model.access.csv',
        'views/res_config_settings_views.xml',
        'views/hr_job_views.xml',
        'views/ethara_candidate_views.xml',
        'views/ethara_lead_views.xml',
        'views/hr_applicant_views.xml',
        'views/hr_applicant_document_views.xml',
        'views/hr_applicant_screening_views.xml',
        'data/candidate_me_endpoints.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
