from odoo.addons.aurora.tools.harness.repos.cpp.bitcoin import *
from odoo.addons.aurora.tools.harness.repos.cpp.capnproto import *
from odoo.addons.aurora.tools.harness.repos.cpp.catchorg import *
from odoo.addons.aurora.tools.harness.repos.cpp.ceph import *
from odoo.addons.aurora.tools.harness.repos.cpp.cgal import *
from odoo.addons.aurora.tools.harness.repos.cpp.fmtlib import *
from odoo.addons.aurora.tools.harness.repos.cpp.halide import *
from odoo.addons.aurora.tools.harness.repos.cpp.nlohmann import *
from odoo.addons.aurora.tools.harness.repos.cpp.microsoft import *
from odoo.addons.aurora.tools.harness.repos.cpp.rootproject import *
from odoo.addons.aurora.tools.harness.repos.cpp.simdjson import *
from odoo.addons.aurora.tools.harness.repos.cpp.yhirose import *
from odoo.addons.aurora.tools.harness.repos.cpp.openmm import *
from odoo.addons.aurora.tools.harness.repos.cpp.PrincetonUniversity import *
from odoo.addons.aurora.tools.harness.repos.cpp.rdkit import *
from odoo.addons.aurora.tools.harness.repos.cpp.einsteintoolkit import *
from odoo.addons.aurora.tools.harness.repos.cpp.AMReXCodes import *
from odoo.addons.aurora.tools.harness.repos.cpp.google import *
from odoo.addons.aurora.tools.harness.repos.cpp.msgpack import *
from odoo.addons.aurora.tools.harness.repos.cpp.duckdb import *
from odoo.addons.aurora.tools.harness.repos.cpp.microsoft import *
from odoo.addons.aurora.tools.harness.repos.cpp.ericniebler import *
from odoo.addons.aurora.tools.harness.repos.cpp.uNetworking import *
from odoo.addons.aurora.tools.harness.repos.cpp.doctest import *
from odoo.addons.aurora.tools.harness.repos.cpp.MariaDB import *
from odoo.addons.aurora.tools.harness.repos.cpp.Neargye import *
