apiVersion: v1
kind: ServiceAccount
metadata:
  name: gohan-worker
  namespace: gohan
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gohan-worker-role
  namespace: gohan
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["create", "get", "update", "patch", "delete", "list"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gohan-worker-binding
  namespace: gohan
subjects:
  - kind: ServiceAccount
    name: gohan-worker
    namespace: gohan
roleRef:
  kind: Role
  name: gohan-worker-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: odoo-pod-role
  namespace: gohan
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["create", "get", "update", "patch", "delete", "replace", "list"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: odoo-pod-binding
  namespace: gohan
subjects:
  - kind: ServiceAccount
    name: default
    namespace: gohan
roleRef:
  kind: Role
  name: odoo-pod-role
  apiGroup: rbac.authorization.k8s.io
