from odoo.addons.aurora.tools.harness.repos.python.pytorch.ignite_3373_to_3240 import *
from odoo.addons.aurora.tools.harness.repos.python.pytorch.ignite_3240_to_2896 import *
from odoo.addons.aurora.tools.harness.repos.python.pytorch.ignite_2369_to_2179 import *
from odoo.addons.aurora.tools.harness.repos.python.pytorch.ignite_2019_to_1756 import *
from odoo.addons.aurora.tools.harness.repos.python.pytorch.ignite_1756_to_1557 import *
from odoo.addons.aurora.tools.harness.repos.python.pytorch.ignite_1238_to_1105 import *
from odoo.addons.aurora.tools.harness.repos.python.pytorch.ignite_563_to_43 import *
from odoo.addons.aurora.tools.harness.repos.python.pytorch.vision_8227_to_6883 import *
from odoo.addons.aurora.tools.harness.repos.python.pytorch.vision_6830_to_6521 import *
from odoo.addons.aurora.tools.harness.repos.python.pytorch.rl_443_to_295 import *
from odoo.addons.aurora.tools.harness.repos.python.pytorch.rl_295_to_148 import *
