from odoo.addons.aurora.tools.harness.repos.python.marimo_team.marimo_5678_to_5548 import *
from odoo.addons.aurora.tools.harness.repos.python.marimo_team.marimo_4524_to_4291 import *
from odoo.addons.aurora.tools.harness.repos.python.marimo_team.marimo_3787_to_2949 import *
from odoo.addons.aurora.tools.harness.repos.python.marimo_team.marimo_2461_to_2326 import *
from odoo.addons.aurora.tools.harness.repos.python.marimo_team.marimo_2326_to_2311 import *
from odoo.addons.aurora.tools.harness.repos.python.marimo_team.marimo_2064_to_1854 import *
from odoo.addons.aurora.tools.harness.repos.python.marimo_team.marimo_1850_to_1713 import *
from odoo.addons.aurora.tools.harness.repos.python.marimo_team.marimo_1713_to_1516 import *
from odoo.addons.aurora.tools.harness.repos.python.marimo_team.marimo_1221_to_807 import *
