from odoo.addons.aurora.tools.harness.repos.python.opensafely_core.ehrql_2505_to_1205 import *
from odoo.addons.aurora.tools.harness.repos.python.opensafely_core.ehrql_903_to_818 import *
from odoo.addons.aurora.tools.harness.repos.python.opensafely_core.ehrql_740_to_576 import *
from odoo.addons.aurora.tools.harness.repos.python.opensafely_core.ehrql_320_to_15 import *
from odoo.addons.aurora.tools.harness.repos.python.opensafely_core.job_server_2420_to_1684 import *
from odoo.addons.aurora.tools.harness.repos.python.opensafely_core.job_server_1473_to_852 import *
from odoo.addons.aurora.tools.harness.repos.python.opensafely_core.job_server_789_to_461 import *
from odoo.addons.aurora.tools.harness.repos.python.opensafely_core.job_server_461_to_395 import *
from odoo.addons.aurora.tools.harness.repos.python.opensafely_core.job_server_274_to_131 import *
from odoo.addons.aurora.tools.harness.repos.python.opensafely_core.job_server_131_to_38 import *
