from odoo.addons.aurora.tools.harness.repos.c.curl import *
from odoo.addons.aurora.tools.harness.repos.c.danmar import *
from odoo.addons.aurora.tools.harness.repos.c.dicedb import *
from odoo.addons.aurora.tools.harness.repos.c.dunst_project import *
from odoo.addons.aurora.tools.harness.repos.c.facebook import *
from odoo.addons.aurora.tools.harness.repos.c.fluent import *
from odoo.addons.aurora.tools.harness.repos.c.Genymobile import *
from odoo.addons.aurora.tools.harness.repos.c.jqlang import *
from odoo.addons.aurora.tools.harness.repos.c.libarchive import *
from odoo.addons.aurora.tools.harness.repos.c.libevent import *
from odoo.addons.aurora.tools.harness.repos.c.libgit2 import *
from odoo.addons.aurora.tools.harness.repos.c.libsdlorg import *
from odoo.addons.aurora.tools.harness.repos.c.Mbed_TLS import *
from odoo.addons.aurora.tools.harness.repos.c.microsoft import *
from odoo.addons.aurora.tools.harness.repos.c.mpv_player import *
from odoo.addons.aurora.tools.harness.repos.c.mruby import *
from odoo.addons.aurora.tools.harness.repos.c.OpenMathLib import *
from odoo.addons.aurora.tools.harness.repos.c.php import *
from odoo.addons.aurora.tools.harness.repos.c.ponylang import *
from odoo.addons.aurora.tools.harness.repos.c.redis import *
from odoo.addons.aurora.tools.harness.repos.c.systemd import *
from odoo.addons.aurora.tools.harness.repos.c.valkey_io import *
from odoo.addons.aurora.tools.harness.repos.c.Wabri import *
from odoo.addons.aurora.tools.harness.repos.c.awslabs import *
from odoo.addons.aurora.tools.harness.repos.c.c_ares import *
