from odoo.addons.aurora.tools.harness.repos.javascript.carbon_design_system.carbon_addons_iot_react_3764_to_3699 import *
from odoo.addons.aurora.tools.harness.repos.javascript.carbon_design_system.ibm_security_682_to_244 import *
from odoo.addons.aurora.tools.harness.repos.javascript.carbon_design_system.ibm_security_196_to_6 import *
from odoo.addons.aurora.tools.harness.repos.javascript.carbon_design_system.carbon_19427_to_16169 import *
from odoo.addons.aurora.tools.harness.repos.javascript.carbon_design_system.ibm_products_7830_to_7681 import *
from odoo.addons.aurora.tools.harness.repos.javascript.carbon_design_system.ibm_products_7666_to_6829 import *
from odoo.addons.aurora.tools.harness.repos.javascript.carbon_design_system.ibm_products_6686_to_6463 import *
from odoo.addons.aurora.tools.harness.repos.javascript.carbon_design_system.ibm_products_5920_to_5761 import *
from odoo.addons.aurora.tools.harness.repos.javascript.carbon_design_system.ibm_products_1316_to_783 import *
