from odoo.addons.aurora.tools.harness.repos.python.pylint_dev.pylint import *
from odoo.addons.aurora.tools.harness.repos.python.pylint_dev.pylint_10860_to_10667 import *
from odoo.addons.aurora.tools.harness.repos.python.pylint_dev.pylint_10641_to_9119 import *
from odoo.addons.aurora.tools.harness.repos.python.pylint_dev.pylint_9084_to_7393 import *
from odoo.addons.aurora.tools.harness.repos.python.pylint_dev.pylint_8824_to_8121 import *
from odoo.addons.aurora.tools.harness.repos.python.pylint_dev.pylint_8121_to_6536 import *
from odoo.addons.aurora.tools.harness.repos.python.pylint_dev.pylint_6480_to_6182 import *
from odoo.addons.aurora.tools.harness.repos.python.pylint_dev.pylint_6182_to_5891 import *
from odoo.addons.aurora.tools.harness.repos.python.pylint_dev.pylint_5891_to_5688 import *
from odoo.addons.aurora.tools.harness.repos.python.pylint_dev.pylint_5688_to_5532 import *
from odoo.addons.aurora.tools.harness.repos.python.pylint_dev.pylint_5464_to_4268 import *
from odoo.addons.aurora.tools.harness.repos.python.pylint_dev.pylint_5446_to_4797 import *
from odoo.addons.aurora.tools.harness.repos.python.pylint_dev.pylint_4769_to_4445 import *
from odoo.addons.aurora.tools.harness.repos.python.pylint_dev.pylint_4398_to_4185 import *
from odoo.addons.aurora.tools.harness.repos.python.pylint_dev.pylint_4104_to_3571 import *
from odoo.addons.aurora.tools.harness.repos.python.pylint_dev.pylint_3654_to_3569 import *
from odoo.addons.aurora.tools.harness.repos.python.pylint_dev.pylint_3311_to_2926 import *
from odoo.addons.aurora.tools.harness.repos.python.pylint_dev.pylint_2926_to_2220 import *
from odoo.addons.aurora.tools.harness.repos.python.pylint_dev.pylint_2630_to_1842 import *
from odoo.addons.aurora.tools.harness.repos.python.pylint_dev.pylint_2090_to_1856 import *
from odoo.addons.aurora.tools.harness.repos.python.pylint_dev.pylint_1745_to_1188 import *
