[service]
name = "amazon-seller-api"
port = 8000
env_var_name = "AMAZON_SELLER_API_URL"
healthcheck_path = "/health"

[k8s]
image = ""
cpu_request = "25m"
memory_request = "128Mi"
memory_limit = "256Mi"
