from odoo.addons.aurora.tools.harness.repos.java.fasterxml.jackson_core import *
from odoo.addons.aurora.tools.harness.repos.java.fasterxml.jackson_databind import *
from odoo.addons.aurora.tools.harness.repos.java.fasterxml.jackson_dataformat_xml import *
from odoo.addons.aurora.tools.harness.repos.java.fasterxml.jackson_databind_5022_to_4968 import *
from odoo.addons.aurora.tools.harness.repos.java.fasterxml.jackson_dataformat_xml_126_to_126 import *
from odoo.addons.aurora.tools.harness.repos.java.fasterxml.jackson_databind_4929_to_4811 import *
from odoo.addons.aurora.tools.harness.repos.java.fasterxml.jackson_databind_4587_to_4418 import *
from odoo.addons.aurora.tools.harness.repos.java.fasterxml.jackson_databind_3622_to_3570 import *
from odoo.addons.aurora.tools.harness.repos.java.fasterxml.jackson_core_1178_to_1171 import *
from odoo.addons.aurora.tools.harness.repos.java.fasterxml.jackson_databind_3140_to_1708 import *
from odoo.addons.aurora.tools.harness.repos.java.fasterxml.jackson_databind_5620_to_4693 import *
from odoo.addons.aurora.tools.harness.repos.java.fasterxml.jackson_databind_5483_to_5175 import *
from odoo.addons.aurora.tools.harness.repos.java.fasterxml.jackson_databind_5714_to_1113 import *
