from odoo.addons.aurora.tools.harness.repos.javascript.LiskHQ.lisk_mobile_1916_to_1911 import *
from odoo.addons.aurora.tools.harness.repos.javascript.LiskHQ.lisk_mobile_1817_to_1786 import *
from odoo.addons.aurora.tools.harness.repos.javascript.LiskHQ.lisk_mobile_1786_to_1780 import *
from odoo.addons.aurora.tools.harness.repos.javascript.LiskHQ.lisk_desktop_5474_to_5376 import *
from odoo.addons.aurora.tools.harness.repos.javascript.LiskHQ.lisk_desktop_5366_to_5324 import *
from odoo.addons.aurora.tools.harness.repos.javascript.LiskHQ.lisk_desktop_5290_to_5252 import *
from odoo.addons.aurora.tools.harness.repos.javascript.LiskHQ.lisk_desktop_5252_to_5176 import *
from odoo.addons.aurora.tools.harness.repos.javascript.LiskHQ.lisk_desktop_5175_to_5135 import *
from odoo.addons.aurora.tools.harness.repos.javascript.LiskHQ.lisk_desktop_5127_to_5108 import *
from odoo.addons.aurora.tools.harness.repos.javascript.LiskHQ.lisk_mobile_1656_to_1630 import *
from odoo.addons.aurora.tools.harness.repos.javascript.LiskHQ.lisk_mobile_1294_to_1040 import *
from odoo.addons.aurora.tools.harness.repos.javascript.LiskHQ.lisk_mobile_715_to_703 import *
from odoo.addons.aurora.tools.harness.repos.javascript.LiskHQ.lisk_mobile_287_to_235 import *
from odoo.addons.aurora.tools.harness.repos.javascript.LiskHQ.lisk_desktop_4513_to_4481 import *
from odoo.addons.aurora.tools.harness.repos.javascript.LiskHQ.lisk_desktop_4185_to_4150 import *
