from odoo.addons.aurora.tools.harness.repos.python.pytest_dev.pytest import *
from odoo.addons.aurora.tools.harness.repos.python.pytest_dev.pytest_2921_to_266 import *
from odoo.addons.aurora.tools.harness.repos.python.pytest_dev.pytest_3642_to_2068 import *
from odoo.addons.aurora.tools.harness.repos.python.pytest_dev.pytest_6391_to_2619 import *
from odoo.addons.aurora.tools.harness.repos.python.pytest_dev.pytest_6234_to_5056 import *
from odoo.addons.aurora.tools.harness.repos.python.pytest_dev.pytest_8632_to_6311 import *
from odoo.addons.aurora.tools.harness.repos.python.pytest_dev.pytest_7199_to_7199 import *
from odoo.addons.aurora.tools.harness.repos.python.pytest_dev.pytest_11546_to_9758 import *
from odoo.addons.aurora.tools.harness.repos.python.pytest_dev.pytest_13533_to_11864 import *
from odoo.addons.aurora.tools.harness.repos.python.pytest_dev.pytest_13952_to_13878 import *
