from . import res_config_settings
from . import hr_job
from . import hr_job_responsibility
from . import hr_job_benefit
from . import hr_job_approver
from . import ethara_candidate
from . import ethara_lead
from . import hr_applicant
from . import hr_applicant_document
from . import hr_applicant_job_history
from . import hr_applicant_reference
from . import res_users
