from odoo.addons.aurora.tools.harness.repos.python.scikit_image.scikit_image_7595_to_4165 import *
from odoo.addons.aurora.tools.harness.repos.python.scikit_image.scikit_image_6892 import *
from odoo.addons.aurora.tools.harness.repos.python.scikit_image.scikit_image_6814 import *
from odoo.addons.aurora.tools.harness.repos.python.scikit_image.scikit_image_6501_to_5999 import *
from odoo.addons.aurora.tools.harness.repos.python.scikit_image.scikit_image_5974_to_5431 import *
from odoo.addons.aurora.tools.harness.repos.python.scikit_image.scikit_image_5349 import *
from odoo.addons.aurora.tools.harness.repos.python.scikit_image.scikit_image_5210_to_5096 import *
from odoo.addons.aurora.tools.harness.repos.python.scikit_image.scikit_image_4875_to_4666 import *
from odoo.addons.aurora.tools.harness.repos.python.scikit_image.scikit_image_4662_to_4289 import *
from odoo.addons.aurora.tools.harness.repos.python.scikit_image.scikit_image_4237 import *
from odoo.addons.aurora.tools.harness.repos.python.scikit_image.scikit_image_4115_to_3901 import *
from odoo.addons.aurora.tools.harness.repos.python.scikit_image.scikit_image_3850_to_3843 import *
from odoo.addons.aurora.tools.harness.repos.python.scikit_image.scikit_image_3809_to_3486 import *
from odoo.addons.aurora.tools.harness.repos.python.scikit_image.scikit_image_3226 import *
from odoo.addons.aurora.tools.harness.repos.python.scikit_image.scikit_image_3031 import *
from odoo.addons.aurora.tools.harness.repos.python.scikit_image.scikit_image_2815_to_2766 import *
from odoo.addons.aurora.tools.harness.repos.python.scikit_image.scikit_image_2761_to_2754 import *
