from odoo.addons.aurora.tools.harness.repos.typescript.ant_design import *
from odoo.addons.aurora.tools.harness.repos.typescript.colinhacks import *
from odoo.addons.aurora.tools.harness.repos.typescript.darkreader import *
from odoo.addons.aurora.tools.harness.repos.typescript.facebook import *
from odoo.addons.aurora.tools.harness.repos.typescript.markedjs import *
from odoo.addons.aurora.tools.harness.repos.typescript.mui import *
from odoo.addons.aurora.tools.harness.repos.typescript.NervJS import *
from odoo.addons.aurora.tools.harness.repos.typescript.nuxt import *
from odoo.addons.aurora.tools.harness.repos.typescript.puppeteer import *
from odoo.addons.aurora.tools.harness.repos.typescript.reduxjs import *
from odoo.addons.aurora.tools.harness.repos.typescript.remix_run import *
from odoo.addons.aurora.tools.harness.repos.typescript.trpc import *
from odoo.addons.aurora.tools.harness.repos.typescript.vuejs import *
from odoo.addons.aurora.tools.harness.repos.typescript.withastro import *
from odoo.addons.aurora.tools.harness.repos.typescript.Automattic import *
from odoo.addons.aurora.tools.harness.repos.typescript.microsoft import *
from odoo.addons.aurora.tools.harness.repos.typescript.MetaMask import *
from odoo.addons.aurora.tools.harness.repos.typescript.palantir import *
from odoo.addons.aurora.tools.harness.repos.typescript.facebook import *
from odoo.addons.aurora.tools.harness.repos.typescript.payloadcms import *
from odoo.addons.aurora.tools.harness.repos.typescript.tradingview import *
from odoo.addons.aurora.tools.harness.repos.typescript.rjsfteam import *
from odoo.addons.aurora.tools.harness.repos.typescript.jestjs import *
from odoo.addons.aurora.tools.harness.repos.typescript.reacthookform import *
from odoo.addons.aurora.tools.harness.repos.typescript.vuetifyjs import *
from odoo.addons.aurora.tools.harness.repos.typescript.highcharts import *
from odoo.addons.aurora.tools.harness.repos.typescript.SocialGouv import *
from odoo.addons.aurora.tools.harness.repos.typescript.aws_amplify import *
from odoo.addons.aurora.tools.harness.repos.typescript.MTES_MCT import *
from odoo.addons.aurora.tools.harness.repos.typescript.bbc import *
from odoo.addons.aurora.tools.harness.repos.typescript.ChainSafe import *
from odoo.addons.aurora.tools.harness.repos.typescript.Joystream import *
from odoo.addons.aurora.tools.harness.repos.typescript.IgniteUI import *
from odoo.addons.aurora.tools.harness.repos.typescript.JoshuaKGoldberg import *
from odoo.addons.aurora.tools.harness.repos.typescript.apache import *
from odoo.addons.aurora.tools.harness.repos.typescript.artifacthub import *
from odoo.addons.aurora.tools.harness.repos.typescript.capricorn86 import *
from odoo.addons.aurora.tools.harness.repos.typescript.Royal_Navy import *
from odoo.addons.aurora.tools.harness.repos.typescript.ONEARMY import *
from odoo.addons.aurora.tools.harness.repos.typescript.angular import *
from odoo.addons.aurora.tools.harness.repos.typescript.PalisadoesFoundation import *
from odoo.addons.aurora.tools.harness.repos.typescript.Northeastern_Electric_Racing import *
from odoo.addons.aurora.tools.harness.repos.typescript.betagouv import *
from odoo.addons.aurora.tools.harness.repos.typescript.cypress_io import *
from odoo.addons.aurora.tools.harness.repos.typescript.Effect_TS import *
from odoo.addons.aurora.tools.harness.repos.typescript.apollographql import *
from odoo.addons.aurora.tools.harness.repos.typescript.Altinn import *
from odoo.addons.aurora.tools.harness.repos.typescript.Azure import *
from odoo.addons.aurora.tools.harness.repos.typescript.BetterThanTomorrow import *
from odoo.addons.aurora.tools.harness.repos.typescript.SwissDataScienceCenter import *
from odoo.addons.aurora.tools.harness.repos.typescript.atlassian_labs import *
from odoo.addons.aurora.tools.harness.repos.typescript.canonical import *
from odoo.addons.aurora.tools.harness.repos.typescript.better_auth import *
from odoo.addons.aurora.tools.harness.repos.typescript.comixed import *
from odoo.addons.aurora.tools.harness.repos.typescript.decaffeinate import *
from odoo.addons.aurora.tools.harness.repos.typescript.allure_framework import *
from odoo.addons.aurora.tools.harness.repos.typescript.PrismJS import *
from odoo.addons.aurora.tools.harness.repos.typescript.ParabolInc import *
from odoo.addons.aurora.tools.harness.repos.typescript.abaplint import *
from odoo.addons.aurora.tools.harness.repos.typescript.apify import *
from odoo.addons.aurora.tools.harness.repos.typescript.antvis import *
from odoo.addons.aurora.tools.harness.repos.typescript.aws_powertools import *
from odoo.addons.aurora.tools.harness.repos.typescript.calcom import *
from odoo.addons.aurora.tools.harness.repos.typescript.Hacker0x01 import *
from odoo.addons.aurora.tools.harness.repos.typescript.HospitalRun import *
from odoo.addons.aurora.tools.harness.repos.typescript.HoudiniGraphql import *
from odoo.addons.aurora.tools.harness.repos.typescript.TypeScriptToLua import *
from odoo.addons.aurora.tools.harness.repos.typescript.Azure import *
from odoo.addons.aurora.tools.harness.repos.typescript.BetterThanTomorrow import *
from odoo.addons.aurora.tools.harness.repos.typescript.RocketChat import *
from odoo.addons.aurora.tools.harness.repos.typescript.RooCodeInc import *
from odoo.addons.aurora.tools.harness.repos.typescript.League_of_Foundry_Developers import *
from odoo.addons.aurora.tools.harness.repos.typescript.VKCOM import *
from odoo.addons.aurora.tools.harness.repos.typescript.defenseunicorns import *
from odoo.addons.aurora.tools.harness.repos.typescript.Safe_DS import *
from odoo.addons.aurora.tools.harness.repos.typescript.SAP import *
from odoo.addons.aurora.tools.harness.repos.typescript.Sage import *
from odoo.addons.aurora.tools.harness.repos.typescript.angular_eslint import *
from odoo.addons.aurora.tools.harness.repos.typescript.arco_design import *
from odoo.addons.aurora.tools.harness.repos.typescript.betagouv import *
from odoo.addons.aurora.tools.harness.repos.typescript.Siteimprove import *
from odoo.addons.aurora.tools.harness.repos.typescript.Shopify import *
from odoo.addons.aurora.tools.harness.repos.typescript.alibaba import *
from odoo.addons.aurora.tools.harness.repos.typescript.apache import *
from odoo.addons.aurora.tools.harness.repos.typescript.cypress_io import *
from odoo.addons.aurora.tools.harness.repos.typescript.deephaven import *
from odoo.addons.aurora.tools.harness.repos.typescript.CommunitySolidServer import *
from odoo.addons.aurora.tools.harness.repos.typescript.DanielXMoore import *
from odoo.addons.aurora.tools.harness.repos.typescript.Tencent import *
from odoo.addons.aurora.tools.harness.repos.typescript.TanStack import *
from odoo.addons.aurora.tools.harness.repos.typescript.TerriaJS import *
from odoo.addons.aurora.tools.harness.repos.typescript.ariakit import *
from odoo.addons.aurora.tools.harness.repos.typescript.blockscout import *
from odoo.addons.aurora.tools.harness.repos.typescript.GMOD import *
from odoo.addons.aurora.tools.harness.repos.typescript.HoudiniGraphql import *
from odoo.addons.aurora.tools.harness.repos.typescript.NomicFoundation import *
from odoo.addons.aurora.tools.harness.repos.typescript.Effect_TS import *
from odoo.addons.aurora.tools.harness.repos.typescript.stakwork import *
from odoo.addons.aurora.tools.harness.repos.typescript.refinedev import *
