{
    "name": "Skoll Backup",
    "version": "19.0.7.0.0",
    "category": "Tools",
    "summary": "Skoll — LLM task management with sandbox environments",
    "description": """
        Skoll custom module for Ethara ETP.
        Local Docker Compose sandbox execution and K8s-native sandbox
        deployments for OpenClaw task environments.
    """,
    "author": "Ethara",
    "depends": ["base", "web", "hr", "bus", "etp_user_roles"],
    "data": [
        "security/skoll_security.xml",
        "security/ir.model.access.csv",
        "views/res_config_settings_views.xml",
        "views/persona_views.xml",
    ],
    "installable": True,
    "application": True,
    "license": "LGPL-3",
    "assets": {
        "web.assets_backend": [
            "skoll_backup/static/src/views/fields/markdown_field/markdown_field.js",
            "skoll_backup/static/src/views/fields/markdown_field/markdown_field.xml",
            "skoll_backup/static/src/views/fields/markdown_field/markdown_field.scss",
            "skoll_backup/static/src/views/fields/json_field/json_field.js",
            "skoll_backup/static/src/views/fields/json_field/json_field.xml",
            "skoll_backup/static/src/views/fields/json_field/json_field.scss",
            "skoll_backup/static/src/sandbox_notification_service.js",
            "skoll_backup/static/src/chat_service.js",
            "skoll_backup/static/src/components/sandbox_iframe/sandbox_iframe.js",
            "skoll_backup/static/src/components/sandbox_iframe/sandbox_iframe.xml",
            "skoll_backup/static/src/components/sandbox_iframe/sandbox_iframe.scss",
            "skoll_backup/static/src/components/task_progress/task_progress.js",
            "skoll_backup/static/src/components/task_progress/task_progress.xml",
            "skoll_backup/static/src/components/task_progress/task_progress.scss",
            "skoll_backup/static/src/chat_widget/chat_widget.js",
            "skoll_backup/static/src/chat_widget/chat_widget.xml",
            "skoll_backup/static/src/chat_widget/chat_widget.scss",
            "skoll_backup/static/src/components/gog_auth_dialog/gog_auth_dialog.js",
            "skoll_backup/static/src/components/gog_auth_dialog/gog_auth_dialog.xml",
            "skoll_backup/static/src/components/gog_auth_dialog/gog_auth_dialog.scss",
            "skoll_backup/static/src/components/sandbox_card/sandbox_card.js",
            "skoll_backup/static/src/components/sandbox_card/sandbox_card.xml",
            "skoll_backup/static/src/components/sandbox_card/sandbox_card.scss",
            "skoll_backup/static/src/task_dashboard/task_dashboard.js",
            "skoll_backup/static/src/task_dashboard/task_dashboard.xml",
            "skoll_backup/static/src/task_dashboard/task_dashboard.scss",
            "skoll_backup/static/src/costing_dashboard/costing_dashboard.js",
            "skoll_backup/static/src/costing_dashboard/costing_dashboard.xml",
            "skoll_backup/static/src/costing_dashboard/costing_dashboard.scss",
        ],
    },
}
