from odoo.addons.aurora.tools.harness.repos.golang.cilium import *
from odoo.addons.aurora.tools.harness.repos.javascript._4ian import *
from odoo.addons.aurora.tools.harness.repos.javascript.Accenture import *
from odoo.addons.aurora.tools.harness.repos.javascript.accordproject import *
from odoo.addons.aurora.tools.harness.repos.javascript.acornjs import *
from odoo.addons.aurora.tools.harness.repos.javascript.adobe import *
from odoo.addons.aurora.tools.harness.repos.javascript.aframevr import *
from odoo.addons.aurora.tools.harness.repos.javascript.Agoric import *
from odoo.addons.aurora.tools.harness.repos.javascript.alam00000 import *
from odoo.addons.aurora.tools.harness.repos.javascript.alibabafusion import *
from odoo.addons.aurora.tools.harness.repos.javascript.alphagov import *
from odoo.addons.aurora.tools.harness.repos.javascript.anuraghazra import *
from odoo.addons.aurora.tools.harness.repos.javascript.aodn import *
from odoo.addons.aurora.tools.harness.repos.javascript.Automattic import *
from odoo.addons.aurora.tools.harness.repos.javascript.avajs import *
from odoo.addons.aurora.tools.harness.repos.javascript.axios import *
from odoo.addons.aurora.tools.harness.repos.javascript.badges import *
from odoo.addons.aurora.tools.harness.repos.javascript.bvaughn import *
from odoo.addons.aurora.tools.harness.repos.javascript.BlakeGuilloud import *
from odoo.addons.aurora.tools.harness.repos.javascript.bpmn_io import *
from odoo.addons.aurora.tools.harness.repos.javascript.bpmnio import *
from odoo.addons.aurora.tools.harness.repos.javascript.brave import *
from odoo.addons.aurora.tools.harness.repos.javascript.camunda import *
from odoo.addons.aurora.tools.harness.repos.javascript.caolan import *
from odoo.addons.aurora.tools.harness.repos.javascript.carbon_design_system import *
from odoo.addons.aurora.tools.harness.repos.javascript.carbondesignsystem import *
from odoo.addons.aurora.tools.harness.repos.javascript.cfpb import *
from odoo.addons.aurora.tools.harness.repos.javascript.chaijs import *
from odoo.addons.aurora.tools.harness.repos.javascript.codemirror import *
from odoo.addons.aurora.tools.harness.repos.javascript.chartjs import *
from odoo.addons.aurora.tools.harness.repos.javascript.City_of_Helsinki import *
from odoo.addons.aurora.tools.harness.repos.javascript.codeceptjs import *
from odoo.addons.aurora.tools.harness.repos.javascript.commercetools import *
from odoo.addons.aurora.tools.harness.repos.javascript.compasjs import *
from odoo.addons.aurora.tools.harness.repos.javascript.CraveFood import *
from odoo.addons.aurora.tools.harness.repos.javascript.cuttle_cards import *
from odoo.addons.aurora.tools.harness.repos.javascript.CVEProject import *
from odoo.addons.aurora.tools.harness.repos.javascript.cylc import *
from odoo.addons.aurora.tools.harness.repos.javascript.DataDog import *
from odoo.addons.aurora.tools.harness.repos.javascript.decred import *
from odoo.addons.aurora.tools.harness.repos.javascript.DevExpress import *
from odoo.addons.aurora.tools.harness.repos.javascript.dinerojs import *
from odoo.addons.aurora.tools.harness.repos.javascript.eslint import *
from odoo.addons.aurora.tools.harness.repos.javascript.exercism import *
from odoo.addons.aurora.tools.harness.repos.javascript.expressjs import *
from odoo.addons.aurora.tools.harness.repos.javascript.facebook import *
from odoo.addons.aurora.tools.harness.repos.javascript.fastify import *
from odoo.addons.aurora.tools.harness.repos.javascript.FlowFuse import *
from odoo.addons.aurora.tools.harness.repos.javascript.google import *
from odoo.addons.aurora.tools.harness.repos.javascript.GoogleChrome import *
from odoo.addons.aurora.tools.harness.repos.javascript.grommet import *
from odoo.addons.aurora.tools.harness.repos.javascript.gsd_build import *
from odoo.addons.aurora.tools.harness.repos.javascript.gulpjs import *
from odoo.addons.aurora.tools.harness.repos.javascript.HabitRPG import *
from odoo.addons.aurora.tools.harness.repos.javascript.hakimel import *
from odoo.addons.aurora.tools.harness.repos.javascript.handsontable import *
from odoo.addons.aurora.tools.harness.repos.javascript.hapijs import *
from odoo.addons.aurora.tools.harness.repos.javascript.highlightjs import *
from odoo.addons.aurora.tools.harness.repos.javascript.iamkun import *
from odoo.addons.aurora.tools.harness.repos.javascript.IgniteUI import *
from odoo.addons.aurora.tools.harness.repos.javascript.jsx_eslint import *
from odoo.addons.aurora.tools.harness.repos.javascript.KaTeX import *
from odoo.addons.aurora.tools.harness.repos.javascript.knex import *
from odoo.addons.aurora.tools.harness.repos.javascript.koajs import *
from odoo.addons.aurora.tools.harness.repos.javascript.Kong import *
from odoo.addons.aurora.tools.harness.repos.javascript.LiskHQ import *
from odoo.addons.aurora.tools.harness.repos.javascript.ManifoldScholar import *
from odoo.addons.aurora.tools.harness.repos.javascript.markedjs import *
from odoo.addons.aurora.tools.harness.repos.javascript.motdotla import *
from odoo.addons.aurora.tools.harness.repos.javascript.nasa import *
from odoo.addons.aurora.tools.harness.repos.javascript.nock import *
from odoo.addons.aurora.tools.harness.repos.javascript.openlayers import *
from odoo.addons.aurora.tools.harness.repos.javascript.postcss import *
from odoo.addons.aurora.tools.harness.repos.javascript.prettier import *
from odoo.addons.aurora.tools.harness.repos.javascript.PrismJS import *
from odoo.addons.aurora.tools.harness.repos.javascript.ProcessMaker import *
from odoo.addons.aurora.tools.harness.repos.javascript.ProjectMirador import *
from odoo.addons.aurora.tools.harness.repos.javascript.quartodev import *
from odoo.addons.aurora.tools.harness.repos.javascript.RaspberryPiFoundation import *
from odoo.addons.aurora.tools.harness.repos.javascript.Real_Dev_Squad import *
from odoo.addons.aurora.tools.harness.repos.javascript.rollup import *
from odoo.addons.aurora.tools.harness.repos.javascript.SchemaStore import *
from odoo.addons.aurora.tools.harness.repos.javascript.scratchfoundation import *
from odoo.addons.aurora.tools.harness.repos.javascript.Semantic_Org import *
from odoo.addons.aurora.tools.harness.repos.javascript.Seneca_CDOT import *
from odoo.addons.aurora.tools.harness.repos.javascript.sinonjs import *
from odoo.addons.aurora.tools.harness.repos.javascript.stdlib_js import *
from odoo.addons.aurora.tools.harness.repos.javascript.sveltejs import *
from odoo.addons.aurora.tools.harness.repos.javascript.swaggerapi import *
from odoo.addons.aurora.tools.harness.repos.javascript.terser import *
from odoo.addons.aurora.tools.harness.repos.javascript.tj import *
from odoo.addons.aurora.tools.harness.repos.javascript.trekhleb import *
from odoo.addons.aurora.tools.harness.repos.javascript.TryGhost import *
from odoo.addons.aurora.tools.harness.repos.javascript.vercel.next_js import *
from odoo.addons.aurora.tools.harness.repos.javascript.videojs import *
from odoo.addons.aurora.tools.harness.repos.javascript.vuejs import *
from odoo.addons.aurora.tools.harness.repos.javascript.webpack.webpack import *
from odoo.addons.aurora.tools.harness.repos.javascript.websockets import *
from odoo.addons.aurora.tools.harness.repos.javascript.gchq import *
from odoo.addons.aurora.tools.harness.repos.javascript.char0n import *
from odoo.addons.aurora.tools.harness.repos.javascript.downshift_js import *
