from odoo.addons.aurora.tools.harness.repos.python.Sceptre.sceptre_v4_4_2 import *
from odoo.addons.aurora.tools.harness.repos.python.Sceptre.sceptre_v1_3_1 import *
from odoo.addons.aurora.tools.harness.repos.python.Sceptre.sceptre_v1_3_4 import *
from odoo.addons.aurora.tools.harness.repos.python.Sceptre.sceptre_v2_6_2 import *
from odoo.addons.aurora.tools.harness.repos.python.Sceptre.sceptre_v1_3_2 import *
from odoo.addons.aurora.tools.harness.repos.python.Sceptre.sceptre_v1_3_3 import *
from odoo.addons.aurora.tools.harness.repos.python.Sceptre.sceptre_v2_0_0rc2 import *
from odoo.addons.aurora.tools.harness.repos.python.Sceptre.sceptre_v4_5_2 import *
from odoo.addons.aurora.tools.harness.repos.python.Sceptre.sceptre_v2_1_1 import *
from odoo.addons.aurora.tools.harness.repos.python.Sceptre.sceptre_v2_7_0 import *
from odoo.addons.aurora.tools.harness.repos.python.Sceptre.sceptre_v2_7_1 import *
from odoo.addons.aurora.tools.harness.repos.python.Sceptre.sceptre_v3_1_0 import *
from odoo.addons.aurora.tools.harness.repos.python.Sceptre.sceptre_v1_4_2 import *
from odoo.addons.aurora.tools.harness.repos.python.Sceptre.sceptre_v1_2_1 import *
from odoo.addons.aurora.tools.harness.repos.python.Sceptre.sceptre_v3_0_0 import *
from odoo.addons.aurora.tools.harness.repos.python.Sceptre.sceptre_v2_1_4 import *
from odoo.addons.aurora.tools.harness.repos.python.Sceptre.sceptre_v1_2_0 import *
from odoo.addons.aurora.tools.harness.repos.python.Sceptre.sceptre_v2_0_0 import *
from odoo.addons.aurora.tools.harness.repos.python.Sceptre.sceptre_v1_1_2 import *
from odoo.addons.aurora.tools.harness.repos.python.Sceptre.sceptre_v1_3_0 import *
from odoo.addons.aurora.tools.harness.repos.python.Sceptre.sceptre_v1_4_1 import *
from odoo.addons.aurora.tools.harness.repos.python.Sceptre.sceptre_v2_6_3 import *
from odoo.addons.aurora.tools.harness.repos.python.Sceptre.sceptre_v4_3_0 import *
from odoo.addons.aurora.tools.harness.repos.python.Sceptre.sceptre_v4_5_1 import *
