from odoo.addons.aurora.tools.harness.repos.python.aio_libs.aiohttp_11132_to_10101 import *
from odoo.addons.aurora.tools.harness.repos.python.aio_libs.aiohttp_9874_to_9566 import *
from odoo.addons.aurora.tools.harness.repos.python.aio_libs.aiohttp_9530_to_9016 import *
from odoo.addons.aurora.tools.harness.repos.python.aio_libs.aiohttp_8951_to_8630 import *
from odoo.addons.aurora.tools.harness.repos.python.aio_libs.aiohttp_8951_to_8630 import *
from odoo.addons.aurora.tools.harness.repos.python.aio_libs.aiohttp_8629_to_8075 import *
from odoo.addons.aurora.tools.harness.repos.python.aio_libs.aiohttp_7908_to_7280 import *
from odoo.addons.aurora.tools.harness.repos.python.aio_libs.aiohttp_7908_to_7280 import *
from odoo.addons.aurora.tools.harness.repos.python.aio_libs.aiohttp_7079_to_6201 import *
from odoo.addons.aurora.tools.harness.repos.python.aio_libs.aiohttp_7079_to_6201 import *
from odoo.addons.aurora.tools.harness.repos.python.aio_libs.aiohttp_5762_to_5731 import *
from odoo.addons.aurora.tools.harness.repos.python.aio_libs.aiohttp_5762_to_5731 import *
from odoo.addons.aurora.tools.harness.repos.python.aio_libs.aiohttp_5731_to_5298 import *
from odoo.addons.aurora.tools.harness.repos.python.aio_libs.aiohttp_5249_to_5157 import *
from odoo.addons.aurora.tools.harness.repos.python.aio_libs.aiohttp_5157_to_4873 import *
from odoo.addons.aurora.tools.harness.repos.python.aio_libs.aiohttp_4813_to_4375 import *
from odoo.addons.aurora.tools.harness.repos.python.aio_libs.aiohttp_4375_to_4046 import *
from odoo.addons.aurora.tools.harness.repos.python.aio_libs.aiohttp_2692_to_2657 import *
from odoo.addons.aurora.tools.harness.repos.python.aio_libs.aiohttp_912_to_908 import *
from odoo.addons.aurora.tools.harness.repos.python.aio_libs.aiohttp_811_to_671 import *
from odoo.addons.aurora.tools.harness.repos.python.aio_libs.aiohttp_488_to_408 import *
