[options]
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = jaeger_dev
addons_path = /opt/ethara/app/addons,/opt/ethara/app/custom_addons
admin_passwd = admin
proxy_mode = True
workers = 2
max_cron_threads = 1
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_time_cpu = 14400
limit_time_real = 28800
http_port = 8069
gevent_port = 8072
