from odoo.addons.aurora.tools.harness.repos.python.PrefectHQ.prefect_18410_to_18363 import *
from odoo.addons.aurora.tools.harness.repos.python.PrefectHQ.prefect_18353_to_17954 import *
from odoo.addons.aurora.tools.harness.repos.python.PrefectHQ.prefect_4462_to_3893 import *
from odoo.addons.aurora.tools.harness.repos.python.PrefectHQ.prefect_3072_to_2666 import *
from odoo.addons.aurora.tools.harness.repos.python.PrefectHQ.prefect_2646_to_2297 import *
from odoo.addons.aurora.tools.harness.repos.python.PrefectHQ.prefect_2228_to_1822 import *
from odoo.addons.aurora.tools.harness.repos.python.PrefectHQ.prefect_1786_to_1673 import *
from odoo.addons.aurora.tools.harness.repos.python.PrefectHQ.prefect_1673_to_1118 import *
from odoo.addons.aurora.tools.harness.repos.python.PrefectHQ.prefect_557_to_532 import *
from odoo.addons.aurora.tools.harness.repos.python.PrefectHQ.prefect_131_to_47 import *
