from odoo.addons.aurora.tools.harness.repos.python.alteryx.featuretools_2705_to_2661 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.featuretools_2459_to_2130 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.featuretools_2102_to_1941 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.featuretools_2102_to_1941 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.featuretools_1733_to_1456 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.featuretools_749_to_688 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.featuretools_679_to_587 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.featuretools_679_to_587 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.featuretools_587_to_511 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.featuretools_479_to_320 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.woodwork_1862_to_1843 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.woodwork_1557_to_1439 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.woodwork_1439_to_1357 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.woodwork_1357_to_1253 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.woodwork_1253_to_806 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.woodwork_700_to_636 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.woodwork_434_to_401 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.woodwork_190_to_105 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.woodwork_105_to_39 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.evalml_2892_to_2820 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.evalml_2126_to_2050 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.evalml_1916_to_1748 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.evalml_1651_to_1566 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.evalml_1566_to_1511 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.evalml_1429_to_1270 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.evalml_904_to_745 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.evalml_741_to_653 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.evalml_650_to_578 import *
from odoo.addons.aurora.tools.harness.repos.python.alteryx.evalml_413_to_42 import *
