from odoo.addons.aurora.tools.harness.repos.rust.alacritty import *
from odoo.addons.aurora.tools.harness.repos.rust.bee_san import *
from odoo.addons.aurora.tools.harness.repos.rust.bitcoindevkit import *
from odoo.addons.aurora.tools.harness.repos.rust.boa_dev import *
from odoo.addons.aurora.tools.harness.repos.rust.casey import *
from odoo.addons.aurora.tools.harness.repos.rust.BurntSushi import *
from odoo.addons.aurora.tools.harness.repos.rust.clap_rs import *
from odoo.addons.aurora.tools.harness.repos.rust.fedimint import *
from odoo.addons.aurora.tools.harness.repos.rust.fish_shell import *
from odoo.addons.aurora.tools.harness.repos.rust.GitoxideLabs import *
from odoo.addons.aurora.tools.harness.repos.rust.golemcloud import *
from odoo.addons.aurora.tools.harness.repos.rust.helix_editor import *
from odoo.addons.aurora.tools.harness.repos.rust.nushell import *
from odoo.addons.aurora.tools.harness.repos.rust.ogham import *
from odoo.addons.aurora.tools.harness.repos.rust.qdrant import *
from odoo.addons.aurora.tools.harness.repos.rust.rayon_rs import *
from odoo.addons.aurora.tools.harness.repos.rust.rusqlite import *
from odoo.addons.aurora.tools.harness.repos.rust.rust_lang import *
from odoo.addons.aurora.tools.harness.repos.rust.SeaQL import *
from odoo.addons.aurora.tools.harness.repos.rust.serde_rs import *
from odoo.addons.aurora.tools.harness.repos.rust.sharkdp import *
from odoo.addons.aurora.tools.harness.repos.rust.starship import *
from odoo.addons.aurora.tools.harness.repos.rust.tailcallhq import *
from odoo.addons.aurora.tools.harness.repos.rust.tauri_apps import *
from odoo.addons.aurora.tools.harness.repos.rust.tokio_rs import *
from odoo.addons.aurora.tools.harness.repos.rust.unicode_org import *
from odoo.addons.aurora.tools.harness.repos.rust.actix import *
from odoo.addons.aurora.tools.harness.repos.rust.hyperium import *
from odoo.addons.aurora.tools.harness.repos.rust.seanmonstar import *
from odoo.addons.aurora.tools.harness.repos.rust.astral_sh import *
from odoo.addons.aurora.tools.harness.repos.rust.ratatui import *
from odoo.addons.aurora.tools.harness.repos.rust.rustls import *
from odoo.addons.aurora.tools.harness.repos.rust.async_graphql import *
from odoo.addons.aurora.tools.harness.repos.rust.dtolnay import *
