{
    "name": "Kensei 2.0",
    "version": "19.0.1.1.0",
    "category": "Tools",
    "summary": "Kensei2 — LLM task management with sandbox environments and file attachments",
    "description": """
        Kensei2 custom module for Ethara ETP.
        Full-featured OpenClaw integration with Docker/K8s sandbox environments.
        Includes file attachment support (images, documents, video) in chat via
        hybrid HTTP upload + WebSocket reference architecture.
    """,
    "author": "Ethara",
    "depends": ["base", "web", "hr", "bus"],
    "data": [
        "security/kensei2_security.xml",
        "security/ir.model.access.csv",
        "data/cron.xml",
        "data/persona_seed.xml",
        "data/domain_seed.xml",
        "views/res_config_settings_views.xml",
        "views/domain_views.xml",
        "views/persona_views.xml",
        "views/kensei2_views.xml",
        "views/api_request_views.xml",
        "views/test_result_views.xml",
        "views/menuitems.xml",
    ],
    "installable": True,
    "application": True,
    "license": "LGPL-3",
    "assets": {
        "web.assets_backend": [
            "kensei2/static/src/views/fields/markdown_field/markdown_field.js",
            "kensei2/static/src/views/fields/markdown_field/markdown_field.xml",
            "kensei2/static/src/views/fields/markdown_field/markdown_field.scss",
            "kensei2/static/src/views/fields/json_field/json_field.js",
            "kensei2/static/src/views/fields/json_field/json_field.xml",
            "kensei2/static/src/views/fields/json_field/json_field.scss",
            "kensei2/static/src/sandbox_notification_service.js",
            "kensei2/static/src/chat_service.js",
            "kensei2/static/src/components/sandbox_iframe/sandbox_iframe.js",
            "kensei2/static/src/components/sandbox_iframe/sandbox_iframe.xml",
            "kensei2/static/src/components/sandbox_iframe/sandbox_iframe.scss",
            "kensei2/static/src/components/task_progress/task_progress.js",
            "kensei2/static/src/components/task_progress/task_progress.xml",
            "kensei2/static/src/components/task_progress/task_progress.scss",
            "kensei2/static/src/chat_widget/chat_widget.js",
            "kensei2/static/src/chat_widget/chat_widget.xml",
            "kensei2/static/src/chat_widget/chat_widget.scss",
            "kensei2/static/src/components/gog_auth_dialog/gog_auth_dialog.js",
            "kensei2/static/src/components/gog_auth_dialog/gog_auth_dialog.xml",
            "kensei2/static/src/components/gog_auth_dialog/gog_auth_dialog.scss",
            "kensei2/static/src/components/sandbox_card/sandbox_card.js",
            "kensei2/static/src/components/sandbox_card/sandbox_card.xml",
            "kensei2/static/src/components/sandbox_card/sandbox_card.scss",
            "kensei2/static/src/task_dashboard/task_dashboard.js",
            "kensei2/static/src/task_dashboard/task_dashboard.xml",
            "kensei2/static/src/task_dashboard/task_dashboard.scss",
            "kensei2/static/src/costing_dashboard/costing_dashboard.js",
            "kensei2/static/src/costing_dashboard/costing_dashboard.xml",
            "kensei2/static/src/costing_dashboard/costing_dashboard.scss",
        ],
    },
}
