from odoo.addons.aurora.tools.harness.repos.python.rotki.rotki_1135_to_1027 import *
from odoo.addons.aurora.tools.harness.repos.python.rotki.rotki_351_to_254 import *
from odoo.addons.aurora.tools.harness.repos.python.rotki.rotki_254_to_143 import *
from odoo.addons.aurora.tools.harness.repos.python.rotki.rotki_978_to_790 import *
from odoo.addons.aurora.tools.harness.repos.python.rotki.rotki_1584_to_1067 import *
from odoo.addons.aurora.tools.harness.repos.python.rotki.rotki_2780_to_1814 import *
from odoo.addons.aurora.tools.harness.repos.python.rotki.rotki_4484_to_3005 import *
from odoo.addons.aurora.tools.harness.repos.python.rotki.rotki_9108_to_6606 import *
from odoo.addons.aurora.tools.harness.repos.python.rotki.rotki_1613_to_902 import *
from odoo.addons.aurora.tools.harness.repos.python.rotki.rotki_4289_to_1871 import *
from odoo.addons.aurora.tools.harness.repos.python.rotki.rotki_4180_to_1269 import *
