FROM python:3.11-slim

RUN pip install --no-cache-dir PyGithub requests boto3 unidiff

COPY custom_addons/jaeger/tools/ /app/tools/
COPY custom_addons/jaeger/worker/entrypoint.py /app/entrypoint.py

WORKDIR /app
CMD ["python", "entrypoint.py"]
