from odoo.addons.aurora.tools.harness.repos.python.scverse.scanpy_1_4 import *
from odoo.addons.aurora.tools.harness.repos.python.scverse.scanpy_1_4_5_1 import *
from odoo.addons.aurora.tools.harness.repos.python.scverse.scanpy_1_8_0_dev0 import *
from odoo.addons.aurora.tools.harness.repos.python.scverse.scanpy_1_3_7 import *
from odoo.addons.aurora.tools.harness.repos.python.scverse.scanpy_1_4_6 import *
from odoo.addons.aurora.tools.harness.repos.python.scverse.scvi_tools_2060_to_1629 import *
from odoo.addons.aurora.tools.harness.repos.python.scverse.scvi_tools_1009_to_705 import *
from odoo.addons.aurora.tools.harness.repos.python.scverse.scvi_tools_705_to_549 import *
from odoo.addons.aurora.tools.harness.repos.python.scverse.scvi_tools_521_to_499 import *
from odoo.addons.aurora.tools.harness.repos.python.scverse.scvi_tools_499_to_477 import *
from odoo.addons.aurora.tools.harness.repos.python.scverse.anndata_1962_to_1724 import *
from odoo.addons.aurora.tools.harness.repos.python.scverse.anndata_1724_to_1631 import *
from odoo.addons.aurora.tools.harness.repos.python.scverse.anndata_1624_to_1550 import *
from odoo.addons.aurora.tools.harness.repos.python.scverse.anndata_763_to_461 import *
from odoo.addons.aurora.tools.harness.repos.python.scverse.anndata_457_to_425 import *
from odoo.addons.aurora.tools.harness.repos.python.scverse.anndata_58_to_24 import *
