from odoo.addons.aurora.tools.harness.repos.python.hgrecco.pint_0_10 import *
from odoo.addons.aurora.tools.harness.repos.python.hgrecco.pint_0_19_2 import *
from odoo.addons.aurora.tools.harness.repos.python.hgrecco.pint_0_19 import *
from odoo.addons.aurora.tools.harness.repos.python.hgrecco.pint_0_4 import *
from odoo.addons.aurora.tools.harness.repos.python.hgrecco.pint_0_20_1 import *
from odoo.addons.aurora.tools.harness.repos.python.hgrecco.pint_0_11 import *
from odoo.addons.aurora.tools.harness.repos.python.hgrecco.pint_0_23rc0 import *
from odoo.addons.aurora.tools.harness.repos.python.hgrecco.pint_0_23 import *
from odoo.addons.aurora.tools.harness.repos.python.hgrecco.pint_0_12 import *
from odoo.addons.aurora.tools.harness.repos.python.hgrecco.pint_0_18 import *
from odoo.addons.aurora.tools.harness.repos.python.hgrecco.pint_0_7_2 import *
from odoo.addons.aurora.tools.harness.repos.python.hgrecco.pint_0_9 import *
