{
    "name": "Loki Clinical Dashboard",
    "version": "19.0.1.0.0",
    "category": "Productivity",
    "summary": "Multi-patient clinical data dashboard — timeline, biomarkers, imaging, WSI",
    "description": """
Loki Clinical Dashboard
========================
Editorial, multi-patient oncology clinical data viewer for Project Loki.

Renders a unified, public portal at /loki2 with ten views per patient:
header, timeline, biomarkers, labs, treatments, imaging, pathology &
molecular, whole-slide images, documents, and a three-patient compare.

Patient data is loaded from data/Clinical_Data/patients.json (hand-authored
fixture or generated by tools/ingest_excel.py). Whole-slide imagery is
served as static Deep Zoom tiles produced offline by tools/generate_dzi.py
(libvips). No runtime libvips dependency.
""",
    "author": "Ethara",
    "license": "LGPL-3",
    "depends": ["base", "portal", "website"],
    "data": [
        "security/ir.model.access.csv",
        "views/res_config_settings_views.xml",
        "views/loki_dashboard_2_menus.xml",
        "views/portal_templates.xml",
    ],
    "assets": {
        "web.assets_backend": [],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
}
