from odoo.addons.aurora.tools.harness.repos.python.pallets.flask import *
from odoo.addons.aurora.tools.harness.repos.python.pallets.flask_5634_to_5058 import *
from odoo.addons.aurora.tools.harness.repos.python.pallets.flask_4621_to_4230 import *
from odoo.addons.aurora.tools.harness.repos.python.pallets.flask_4113_to_3726 import *
from odoo.addons.aurora.tools.harness.repos.python.pallets.flask_3563_to_3124 import *
from odoo.addons.aurora.tools.harness.repos.python.pallets.flask_2765_to_1593 import *
from odoo.addons.aurora.tools.harness.repos.python.pallets.click_2956_to_2840 import *
from odoo.addons.aurora.tools.harness.repos.python.pallets.click_2800_to_1400 import *
from odoo.addons.aurora.tools.harness.repos.python.pallets.click_1400_to_123 import *
from odoo.addons.aurora.tools.harness.repos.python.pallets.werkzeug_1065_to_1062 import *
from odoo.addons.aurora.tools.harness.repos.python.pallets.werkzeug_2509_to_1286 import *
from odoo.addons.aurora.tools.harness.repos.python.pallets.werkzeug_3085_to_2656 import *
